// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ChatRoomMemberInfo extends Table {
  public static ChatRoomMemberInfo getRootAsChatRoomMemberInfo(ByteBuffer _bb) { return getRootAsChatRoomMemberInfo(_bb, new ChatRoomMemberInfo()); }
  public static ChatRoomMemberInfo getRootAsChatRoomMemberInfo(ByteBuffer _bb, ChatRoomMemberInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ChatRoomMemberInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String uid() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer uidAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String roomId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roomIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public long lastOrder() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long atOrders(int j) { int o = __offset(10); return o != 0 ? bb.getLong(__vector(o) + j * 8) : 0; }
  public int atOrdersLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer atOrdersAsByteBuffer() { return __vector_as_bytebuffer(10, 8); }
  public long state() { int o = __offset(12); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createChatRoomMemberInfo(FlatBufferBuilder builder,
      int uidOffset,
      int roomIdOffset,
      long lastOrder,
      int atOrdersOffset,
      long state) {
    builder.startObject(5);
    ChatRoomMemberInfo.addLastOrder(builder, lastOrder);
    ChatRoomMemberInfo.addState(builder, state);
    ChatRoomMemberInfo.addAtOrders(builder, atOrdersOffset);
    ChatRoomMemberInfo.addRoomId(builder, roomIdOffset);
    ChatRoomMemberInfo.addUid(builder, uidOffset);
    return ChatRoomMemberInfo.endChatRoomMemberInfo(builder);
  }

  public static void startChatRoomMemberInfo(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addUid(FlatBufferBuilder builder, int uidOffset) { builder.addOffset(0, uidOffset, 0); }
  public static void addRoomId(FlatBufferBuilder builder, int roomIdOffset) { builder.addOffset(1, roomIdOffset, 0); }
  public static void addLastOrder(FlatBufferBuilder builder, long lastOrder) { builder.addLong(2, lastOrder, 0L); }
  public static void addAtOrders(FlatBufferBuilder builder, int atOrdersOffset) { builder.addOffset(3, atOrdersOffset, 0); }
  public static int createAtOrdersVector(FlatBufferBuilder builder, long[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addLong(data[i]); return builder.endVector(); }
  public static void startAtOrdersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static void addState(FlatBufferBuilder builder, long state) { builder.addInt(4, (int)state, (int)0L); }
  public static int endChatRoomMemberInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

