// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ChatMessageInfo extends Table {
  public static ChatMessageInfo getRootAsChatMessageInfo(ByteBuffer _bb) { return getRootAsChatMessageInfo(_bb, new ChatMessageInfo()); }
  public static ChatMessageInfo getRootAsChatMessageInfo(ByteBuffer _bb, ChatMessageInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ChatMessageInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String roomId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roomIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public long order() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String uid() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer uidAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public String atUids(int j) { int o = __offset(10); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int atUidsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public long sendedTime() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long receivedTime() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long contentType() { int o = __offset(16); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String content() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public MessageContent translation(int j) { return translation(new MessageContent(), j); }
  public MessageContent translation(MessageContent obj, int j) { int o = __offset(20); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int translationLength() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public String clientExt() { int o = __offset(22); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer clientExtAsByteBuffer() { return __vector_as_bytebuffer(22, 1); }
  public String serverExt() { int o = __offset(24); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer serverExtAsByteBuffer() { return __vector_as_bytebuffer(24, 1); }

  public static int createChatMessageInfo(FlatBufferBuilder builder,
      int roomIdOffset,
      long order,
      int uidOffset,
      int atUidsOffset,
      long sendedTime,
      long receivedTime,
      long contentType,
      int contentOffset,
      int translationOffset,
      int clientExtOffset,
      int serverExtOffset) {
    builder.startObject(11);
    ChatMessageInfo.addReceivedTime(builder, receivedTime);
    ChatMessageInfo.addSendedTime(builder, sendedTime);
    ChatMessageInfo.addOrder(builder, order);
    ChatMessageInfo.addServerExt(builder, serverExtOffset);
    ChatMessageInfo.addClientExt(builder, clientExtOffset);
    ChatMessageInfo.addTranslation(builder, translationOffset);
    ChatMessageInfo.addContent(builder, contentOffset);
    ChatMessageInfo.addContentType(builder, contentType);
    ChatMessageInfo.addAtUids(builder, atUidsOffset);
    ChatMessageInfo.addUid(builder, uidOffset);
    ChatMessageInfo.addRoomId(builder, roomIdOffset);
    return ChatMessageInfo.endChatMessageInfo(builder);
  }

  public static void startChatMessageInfo(FlatBufferBuilder builder) { builder.startObject(11); }
  public static void addRoomId(FlatBufferBuilder builder, int roomIdOffset) { builder.addOffset(0, roomIdOffset, 0); }
  public static void addOrder(FlatBufferBuilder builder, long order) { builder.addLong(1, order, 0L); }
  public static void addUid(FlatBufferBuilder builder, int uidOffset) { builder.addOffset(2, uidOffset, 0); }
  public static void addAtUids(FlatBufferBuilder builder, int atUidsOffset) { builder.addOffset(3, atUidsOffset, 0); }
  public static int createAtUidsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAtUidsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addSendedTime(FlatBufferBuilder builder, long sendedTime) { builder.addLong(4, sendedTime, 0L); }
  public static void addReceivedTime(FlatBufferBuilder builder, long receivedTime) { builder.addLong(5, receivedTime, 0L); }
  public static void addContentType(FlatBufferBuilder builder, long contentType) { builder.addInt(6, (int)contentType, (int)0L); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(7, contentOffset, 0); }
  public static void addTranslation(FlatBufferBuilder builder, int translationOffset) { builder.addOffset(8, translationOffset, 0); }
  public static int createTranslationVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTranslationVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addClientExt(FlatBufferBuilder builder, int clientExtOffset) { builder.addOffset(9, clientExtOffset, 0); }
  public static void addServerExt(FlatBufferBuilder builder, int serverExtOffset) { builder.addOffset(10, serverExtOffset, 0); }
  public static int endChatMessageInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

