// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ChatRoomInfo extends Table {
  public static ChatRoomInfo getRootAsChatRoomInfo(ByteBuffer _bb) { return getRootAsChatRoomInfo(_bb, new ChatRoomInfo()); }
  public static ChatRoomInfo getRootAsChatRoomInfo(ByteBuffer _bb, ChatRoomInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ChatRoomInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String roomId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roomIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public long roomType() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String admin() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer adminAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public long createTime() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String name() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }

  public static int createChatRoomInfo(FlatBufferBuilder builder,
      int roomIdOffset,
      long roomType,
      int adminOffset,
      long createTime,
      int nameOffset) {
    builder.startObject(5);
    ChatRoomInfo.addCreateTime(builder, createTime);
    ChatRoomInfo.addName(builder, nameOffset);
    ChatRoomInfo.addAdmin(builder, adminOffset);
    ChatRoomInfo.addRoomType(builder, roomType);
    ChatRoomInfo.addRoomId(builder, roomIdOffset);
    return ChatRoomInfo.endChatRoomInfo(builder);
  }

  public static void startChatRoomInfo(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addRoomId(FlatBufferBuilder builder, int roomIdOffset) { builder.addOffset(0, roomIdOffset, 0); }
  public static void addRoomType(FlatBufferBuilder builder, long roomType) { builder.addInt(1, (int)roomType, (int)0L); }
  public static void addAdmin(FlatBufferBuilder builder, int adminOffset) { builder.addOffset(2, adminOffset, 0); }
  public static void addCreateTime(FlatBufferBuilder builder, long createTime) { builder.addLong(3, createTime, 0L); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(4, nameOffset, 0); }
  public static int endChatRoomInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

