// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

public final class CommondId_Chat {
  private CommondId_Chat() { }
  public static final int CreateChatRoomUp = 20001;
  public static final int CreateChatRoomDown = 20002;
  public static final int ManagerChatRoomMemberUp = 20003;
  public static final int ManagerChatRoomMemberDown = 20004;
  public static final int GainChatMessageUp = 20021;
  public static final int GainChatMessageDown = 20022;
  public static final int SendChatMessageUp = 20023;
  public static final int SendChatMessageDown = 20024;
  public static final int TranslationMessageUp = 20025;
  public static final int TranslationMessageDown = 20026;

  public static final String[] names = { "CreateChatRoomUp", "CreateChatRoomDown", "ManagerChatRoomMemberUp", "ManagerChatRoomMemberDown", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "GainChatMessageUp", "GainChatMessageDown", "SendChatMessageUp", "SendChatMessageDown", "TranslationMessageUp", "TranslationMessageDown", };

  public static String name(int e) { return names[e - CreateChatRoomUp]; }
}

