// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

public final class CommondId_Error {
  private CommondId_Error() { }
  public static final int ErrorMessageDown = 90001;
  public static final int SuccessMessageDown = 90002;

  public static final String[] names = { "ErrorMessageDown", "SuccessMessageDown", };

  public static String name(int e) { return names[e - ErrorMessageDown]; }
}

