// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

public final class CommondId_User {
  private CommondId_User() { }
  public static final int UserLoginUp = 10001;
  public static final int UserLoginDown = 10002;
  public static final int UserLogoutUp = 10003;
  public static final int ModifyLanguageUp = 10004;

  public static final String[] names = { "UserLoginUp", "UserLoginDown", "UserLogoutUp", "ModifyLanguageUp", };

  public static String name(int e) { return names[e - UserLoginUp]; }
}

