// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ErrorMessageDown extends Table {
  public static ErrorMessageDown getRootAsErrorMessageDown(ByteBuffer _bb) { return getRootAsErrorMessageDown(_bb, new ErrorMessageDown()); }
  public static ErrorMessageDown getRootAsErrorMessageDown(ByteBuffer _bb, ErrorMessageDown obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ErrorMessageDown __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long errorType() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long errorDetail() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long commandId() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createErrorMessageDown(FlatBufferBuilder builder,
      long errorType,
      long errorDetail,
      long commandId) {
    builder.startObject(3);
    ErrorMessageDown.addCommandId(builder, commandId);
    ErrorMessageDown.addErrorDetail(builder, errorDetail);
    ErrorMessageDown.addErrorType(builder, errorType);
    return ErrorMessageDown.endErrorMessageDown(builder);
  }

  public static void startErrorMessageDown(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addErrorType(FlatBufferBuilder builder, long errorType) { builder.addInt(0, (int)errorType, (int)0L); }
  public static void addErrorDetail(FlatBufferBuilder builder, long errorDetail) { builder.addInt(1, (int)errorDetail, (int)0L); }
  public static void addCommandId(FlatBufferBuilder builder, long commandId) { builder.addInt(2, (int)commandId, (int)0L); }
  public static int endErrorMessageDown(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

