// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GainChatMessageUp extends Table {
  public static GainChatMessageUp getRootAsGainChatMessageUp(ByteBuffer _bb) { return getRootAsGainChatMessageUp(_bb, new GainChatMessageUp()); }
  public static GainChatMessageUp getRootAsGainChatMessageUp(ByteBuffer _bb, GainChatMessageUp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public GainChatMessageUp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String uid() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer uidAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public long gainType() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long sendedTime() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public AllNewestCondition allNewest() { return allNewest(new AllNewestCondition()); }
  public AllNewestCondition allNewest(AllNewestCondition obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public RoomMultiCondition roomMulti() { return roomMulti(new RoomMultiCondition()); }
  public RoomMultiCondition roomMulti(RoomMultiCondition obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public RoomPageCondition roomPage() { return roomPage(new RoomPageCondition()); }
  public RoomPageCondition roomPage(RoomPageCondition obj) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public RoomNewestCondition roomNewest() { return roomNewest(new RoomNewestCondition()); }
  public RoomNewestCondition roomNewest(RoomNewestCondition obj) { int o = __offset(16); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createGainChatMessageUp(FlatBufferBuilder builder,
      int uidOffset,
      long gainType,
      long sendedTime,
      int allNewestOffset,
      int roomMultiOffset,
      int roomPageOffset,
      int roomNewestOffset) {
    builder.startObject(7);
    GainChatMessageUp.addSendedTime(builder, sendedTime);
    GainChatMessageUp.addRoomNewest(builder, roomNewestOffset);
    GainChatMessageUp.addRoomPage(builder, roomPageOffset);
    GainChatMessageUp.addRoomMulti(builder, roomMultiOffset);
    GainChatMessageUp.addAllNewest(builder, allNewestOffset);
    GainChatMessageUp.addGainType(builder, gainType);
    GainChatMessageUp.addUid(builder, uidOffset);
    return GainChatMessageUp.endGainChatMessageUp(builder);
  }

  public static void startGainChatMessageUp(FlatBufferBuilder builder) { builder.startObject(7); }
  public static void addUid(FlatBufferBuilder builder, int uidOffset) { builder.addOffset(0, uidOffset, 0); }
  public static void addGainType(FlatBufferBuilder builder, long gainType) { builder.addInt(1, (int)gainType, (int)0L); }
  public static void addSendedTime(FlatBufferBuilder builder, long sendedTime) { builder.addLong(2, sendedTime, 0L); }
  public static void addAllNewest(FlatBufferBuilder builder, int allNewestOffset) { builder.addOffset(3, allNewestOffset, 0); }
  public static void addRoomMulti(FlatBufferBuilder builder, int roomMultiOffset) { builder.addOffset(4, roomMultiOffset, 0); }
  public static void addRoomPage(FlatBufferBuilder builder, int roomPageOffset) { builder.addOffset(5, roomPageOffset, 0); }
  public static void addRoomNewest(FlatBufferBuilder builder, int roomNewestOffset) { builder.addOffset(6, roomNewestOffset, 0); }
  public static int endGainChatMessageUp(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

