// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ManagerChatRoomMemberDown extends Table {
  public static ManagerChatRoomMemberDown getRootAsManagerChatRoomMemberDown(ByteBuffer _bb) { return getRootAsManagerChatRoomMemberDown(_bb, new ManagerChatRoomMemberDown()); }
  public static ManagerChatRoomMemberDown getRootAsManagerChatRoomMemberDown(ByteBuffer _bb, ManagerChatRoomMemberDown obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ManagerChatRoomMemberDown __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long modifyType() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String roomId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roomIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String uid(int j) { int o = __offset(8); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int uidLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public long roomType() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createManagerChatRoomMemberDown(FlatBufferBuilder builder,
      long modifyType,
      int roomIdOffset,
      int uidOffset,
      long roomType) {
    builder.startObject(4);
    ManagerChatRoomMemberDown.addRoomType(builder, roomType);
    ManagerChatRoomMemberDown.addUid(builder, uidOffset);
    ManagerChatRoomMemberDown.addRoomId(builder, roomIdOffset);
    ManagerChatRoomMemberDown.addModifyType(builder, modifyType);
    return ManagerChatRoomMemberDown.endManagerChatRoomMemberDown(builder);
  }

  public static void startManagerChatRoomMemberDown(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addModifyType(FlatBufferBuilder builder, long modifyType) { builder.addInt(0, (int)modifyType, (int)0L); }
  public static void addRoomId(FlatBufferBuilder builder, int roomIdOffset) { builder.addOffset(1, roomIdOffset, 0); }
  public static void addUid(FlatBufferBuilder builder, int uidOffset) { builder.addOffset(2, uidOffset, 0); }
  public static int createUidVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startUidVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addRoomType(FlatBufferBuilder builder, long roomType) { builder.addInt(3, (int)roomType, (int)0L); }
  public static int endManagerChatRoomMemberDown(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

