// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ModifyLanguageUp extends Table {
  public static ModifyLanguageUp getRootAsModifyLanguageUp(ByteBuffer _bb) { return getRootAsModifyLanguageUp(_bb, new ModifyLanguageUp()); }
  public static ModifyLanguageUp getRootAsModifyLanguageUp(ByteBuffer _bb, ModifyLanguageUp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ModifyLanguageUp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String languageType() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer languageTypeAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createModifyLanguageUp(FlatBufferBuilder builder,
      int languageTypeOffset) {
    builder.startObject(1);
    ModifyLanguageUp.addLanguageType(builder, languageTypeOffset);
    return ModifyLanguageUp.endModifyLanguageUp(builder);
  }

  public static void startModifyLanguageUp(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addLanguageType(FlatBufferBuilder builder, int languageTypeOffset) { builder.addOffset(0, languageTypeOffset, 0); }
  public static int endModifyLanguageUp(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

