// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RoomMultiCondition extends Table {
  public static RoomMultiCondition getRootAsRoomMultiCondition(ByteBuffer _bb) { return getRootAsRoomMultiCondition(_bb, new RoomMultiCondition()); }
  public static RoomMultiCondition getRootAsRoomMultiCondition(ByteBuffer _bb, RoomMultiCondition obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public RoomMultiCondition __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String roomId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roomIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public long roomType() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long order(int j) { int o = __offset(8); return o != 0 ? bb.getLong(__vector(o) + j * 8) : 0; }
  public int orderLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer orderAsByteBuffer() { return __vector_as_bytebuffer(8, 8); }

  public static int createRoomMultiCondition(FlatBufferBuilder builder,
      int roomIdOffset,
      long roomType,
      int orderOffset) {
    builder.startObject(3);
    RoomMultiCondition.addOrder(builder, orderOffset);
    RoomMultiCondition.addRoomType(builder, roomType);
    RoomMultiCondition.addRoomId(builder, roomIdOffset);
    return RoomMultiCondition.endRoomMultiCondition(builder);
  }

  public static void startRoomMultiCondition(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addRoomId(FlatBufferBuilder builder, int roomIdOffset) { builder.addOffset(0, roomIdOffset, 0); }
  public static void addRoomType(FlatBufferBuilder builder, long roomType) { builder.addInt(1, (int)roomType, (int)0L); }
  public static void addOrder(FlatBufferBuilder builder, int orderOffset) { builder.addOffset(2, orderOffset, 0); }
  public static int createOrderVector(FlatBufferBuilder builder, long[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addLong(data[i]); return builder.endVector(); }
  public static void startOrderVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static int endRoomMultiCondition(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

