// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RoomNewestCondition extends Table {
  public static RoomNewestCondition getRootAsRoomNewestCondition(ByteBuffer _bb) { return getRootAsRoomNewestCondition(_bb, new RoomNewestCondition()); }
  public static RoomNewestCondition getRootAsRoomNewestCondition(ByteBuffer _bb, RoomNewestCondition obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public RoomNewestCondition __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String roomId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roomIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public long roomType() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createRoomNewestCondition(FlatBufferBuilder builder,
      int roomIdOffset,
      long roomType) {
    builder.startObject(2);
    RoomNewestCondition.addRoomType(builder, roomType);
    RoomNewestCondition.addRoomId(builder, roomIdOffset);
    return RoomNewestCondition.endRoomNewestCondition(builder);
  }

  public static void startRoomNewestCondition(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addRoomId(FlatBufferBuilder builder, int roomIdOffset) { builder.addOffset(0, roomIdOffset, 0); }
  public static void addRoomType(FlatBufferBuilder builder, long roomType) { builder.addInt(1, (int)roomType, (int)0L); }
  public static int endRoomNewestCondition(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

