// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RoomPageCondition extends Table {
  public static RoomPageCondition getRootAsRoomPageCondition(ByteBuffer _bb) { return getRootAsRoomPageCondition(_bb, new RoomPageCondition()); }
  public static RoomPageCondition getRootAsRoomPageCondition(ByteBuffer _bb, RoomPageCondition obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public RoomPageCondition __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String roomId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roomIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public long roomType() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long order() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long count() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public boolean isNewest() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createRoomPageCondition(FlatBufferBuilder builder,
      int roomIdOffset,
      long roomType,
      long order,
      long count,
      boolean isNewest) {
    builder.startObject(5);
    RoomPageCondition.addOrder(builder, order);
    RoomPageCondition.addCount(builder, count);
    RoomPageCondition.addRoomType(builder, roomType);
    RoomPageCondition.addRoomId(builder, roomIdOffset);
    RoomPageCondition.addIsNewest(builder, isNewest);
    return RoomPageCondition.endRoomPageCondition(builder);
  }

  public static void startRoomPageCondition(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addRoomId(FlatBufferBuilder builder, int roomIdOffset) { builder.addOffset(0, roomIdOffset, 0); }
  public static void addRoomType(FlatBufferBuilder builder, long roomType) { builder.addInt(1, (int)roomType, (int)0L); }
  public static void addOrder(FlatBufferBuilder builder, long order) { builder.addLong(2, order, 0L); }
  public static void addCount(FlatBufferBuilder builder, long count) { builder.addInt(3, (int)count, (int)0L); }
  public static void addIsNewest(FlatBufferBuilder builder, boolean isNewest) { builder.addBoolean(4, isNewest, false); }
  public static int endRoomPageCondition(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

