// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SendChatMessageUp extends Table {
  public static SendChatMessageUp getRootAsSendChatMessageUp(ByteBuffer _bb) { return getRootAsSendChatMessageUp(_bb, new SendChatMessageUp()); }
  public static SendChatMessageUp getRootAsSendChatMessageUp(ByteBuffer _bb, SendChatMessageUp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SendChatMessageUp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String uid() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer uidAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public long contentType() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String content() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public long sendedTime() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long roomType() { int o = __offset(12); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String roomId() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roomIdAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public String atUids(int j) { int o = __offset(16); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int atUidsLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }
  public String targetUid() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer targetUidAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public String clientExt() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer clientExtAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public String serverExt() { int o = __offset(22); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer serverExtAsByteBuffer() { return __vector_as_bytebuffer(22, 1); }

  public static int createSendChatMessageUp(FlatBufferBuilder builder,
      int uidOffset,
      long contentType,
      int contentOffset,
      long sendedTime,
      long roomType,
      int roomIdOffset,
      int atUidsOffset,
      int targetUidOffset,
      int clientExtOffset,
      int serverExtOffset) {
    builder.startObject(10);
    SendChatMessageUp.addSendedTime(builder, sendedTime);
    SendChatMessageUp.addServerExt(builder, serverExtOffset);
    SendChatMessageUp.addClientExt(builder, clientExtOffset);
    SendChatMessageUp.addTargetUid(builder, targetUidOffset);
    SendChatMessageUp.addAtUids(builder, atUidsOffset);
    SendChatMessageUp.addRoomId(builder, roomIdOffset);
    SendChatMessageUp.addRoomType(builder, roomType);
    SendChatMessageUp.addContent(builder, contentOffset);
    SendChatMessageUp.addContentType(builder, contentType);
    SendChatMessageUp.addUid(builder, uidOffset);
    return SendChatMessageUp.endSendChatMessageUp(builder);
  }

  public static void startSendChatMessageUp(FlatBufferBuilder builder) { builder.startObject(10); }
  public static void addUid(FlatBufferBuilder builder, int uidOffset) { builder.addOffset(0, uidOffset, 0); }
  public static void addContentType(FlatBufferBuilder builder, long contentType) { builder.addInt(1, (int)contentType, (int)0L); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(2, contentOffset, 0); }
  public static void addSendedTime(FlatBufferBuilder builder, long sendedTime) { builder.addLong(3, sendedTime, 0L); }
  public static void addRoomType(FlatBufferBuilder builder, long roomType) { builder.addInt(4, (int)roomType, (int)0L); }
  public static void addRoomId(FlatBufferBuilder builder, int roomIdOffset) { builder.addOffset(5, roomIdOffset, 0); }
  public static void addAtUids(FlatBufferBuilder builder, int atUidsOffset) { builder.addOffset(6, atUidsOffset, 0); }
  public static int createAtUidsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAtUidsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addTargetUid(FlatBufferBuilder builder, int targetUidOffset) { builder.addOffset(7, targetUidOffset, 0); }
  public static void addClientExt(FlatBufferBuilder builder, int clientExtOffset) { builder.addOffset(8, clientExtOffset, 0); }
  public static void addServerExt(FlatBufferBuilder builder, int serverExtOffset) { builder.addOffset(9, serverExtOffset, 0); }
  public static int endSendChatMessageUp(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

