// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SendChatMessageDown extends Table {
  public static SendChatMessageDown getRootAsSendChatMessageDown(ByteBuffer _bb) { return getRootAsSendChatMessageDown(_bb, new SendChatMessageDown()); }
  public static SendChatMessageDown getRootAsSendChatMessageDown(ByteBuffer _bb, SendChatMessageDown obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SendChatMessageDown __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ChatRoomInfo chatRoom() { return chatRoom(new ChatRoomInfo()); }
  public ChatRoomInfo chatRoom(ChatRoomInfo obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public ChatMessageInfo chatMessage() { return chatMessage(new ChatMessageInfo()); }
  public ChatMessageInfo chatMessage(ChatMessageInfo obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public long roomType() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createSendChatMessageDown(FlatBufferBuilder builder,
      int chatRoomOffset,
      int chatMessageOffset,
      long roomType) {
    builder.startObject(3);
    SendChatMessageDown.addRoomType(builder, roomType);
    SendChatMessageDown.addChatMessage(builder, chatMessageOffset);
    SendChatMessageDown.addChatRoom(builder, chatRoomOffset);
    return SendChatMessageDown.endSendChatMessageDown(builder);
  }

  public static void startSendChatMessageDown(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addChatRoom(FlatBufferBuilder builder, int chatRoomOffset) { builder.addOffset(0, chatRoomOffset, 0); }
  public static void addChatMessage(FlatBufferBuilder builder, int chatMessageOffset) { builder.addOffset(1, chatMessageOffset, 0); }
  public static void addRoomType(FlatBufferBuilder builder, long roomType) { builder.addInt(2, (int)roomType, (int)0L); }
  public static int endSendChatMessageDown(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

