// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SuccessMessageDown extends Table {
  public static SuccessMessageDown getRootAsSuccessMessageDown(ByteBuffer _bb) { return getRootAsSuccessMessageDown(_bb, new SuccessMessageDown()); }
  public static SuccessMessageDown getRootAsSuccessMessageDown(ByteBuffer _bb, SuccessMessageDown obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SuccessMessageDown __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long commandId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createSuccessMessageDown(FlatBufferBuilder builder,
      long commandId) {
    builder.startObject(1);
    SuccessMessageDown.addCommandId(builder, commandId);
    return SuccessMessageDown.endSuccessMessageDown(builder);
  }

  public static void startSuccessMessageDown(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addCommandId(FlatBufferBuilder builder, long commandId) { builder.addInt(0, (int)commandId, (int)0L); }
  public static int endSuccessMessageDown(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

