// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TranslationMessageUp extends Table {
  public static TranslationMessageUp getRootAsTranslationMessageUp(ByteBuffer _bb) { return getRootAsTranslationMessageUp(_bb, new TranslationMessageUp()); }
  public static TranslationMessageUp getRootAsTranslationMessageUp(ByteBuffer _bb, TranslationMessageUp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public TranslationMessageUp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String roomId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roomIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public long order() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long roomType() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createTranslationMessageUp(FlatBufferBuilder builder,
      int roomIdOffset,
      long order,
      long roomType) {
    builder.startObject(3);
    TranslationMessageUp.addOrder(builder, order);
    TranslationMessageUp.addRoomType(builder, roomType);
    TranslationMessageUp.addRoomId(builder, roomIdOffset);
    return TranslationMessageUp.endTranslationMessageUp(builder);
  }

  public static void startTranslationMessageUp(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addRoomId(FlatBufferBuilder builder, int roomIdOffset) { builder.addOffset(0, roomIdOffset, 0); }
  public static void addOrder(FlatBufferBuilder builder, long order) { builder.addLong(1, order, 0L); }
  public static void addRoomType(FlatBufferBuilder builder, long roomType) { builder.addInt(2, (int)roomType, (int)0L); }
  public static int endTranslationMessageUp(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

