// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UserLogoutUp extends Table {
  public static UserLogoutUp getRootAsUserLogoutUp(ByteBuffer _bb) { return getRootAsUserLogoutUp(_bb, new UserLogoutUp()); }
  public static UserLogoutUp getRootAsUserLogoutUp(ByteBuffer _bb, UserLogoutUp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public UserLogoutUp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long userId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createUserLogoutUp(FlatBufferBuilder builder,
      long userId) {
    builder.startObject(1);
    UserLogoutUp.addUserId(builder, userId);
    return UserLogoutUp.endUserLogoutUp(builder);
  }

  public static void startUserLogoutUp(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addUserId(FlatBufferBuilder builder, long userId) { builder.addLong(0, userId, 0L); }
  public static int endUserLogoutUp(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

