// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UserLoginDown extends Table {
  public static UserLoginDown getRootAsUserLoginDown(ByteBuffer _bb) { return getRootAsUserLoginDown(_bb, new UserLoginDown()); }
  public static UserLoginDown getRootAsUserLoginDown(ByteBuffer _bb, UserLoginDown obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public UserLoginDown __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long userType() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String functionType() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer functionTypeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String sid() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sidAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }

  public static int createUserLoginDown(FlatBufferBuilder builder,
      long userType,
      int functionTypeOffset,
      int sidOffset) {
    builder.startObject(3);
    UserLoginDown.addUserType(builder, userType);
    UserLoginDown.addSid(builder, sidOffset);
    UserLoginDown.addFunctionType(builder, functionTypeOffset);
    return UserLoginDown.endUserLoginDown(builder);
  }

  public static void startUserLoginDown(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addUserType(FlatBufferBuilder builder, long userType) { builder.addLong(0, userType, 0L); }
  public static void addFunctionType(FlatBufferBuilder builder, int functionTypeOffset) { builder.addOffset(1, functionTypeOffset, 0); }
  public static void addSid(FlatBufferBuilder builder, int sidOffset) { builder.addOffset(2, sidOffset, 0); }
  public static int endUserLoginDown(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

