// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UserLoginUp extends Table {
  public static UserLoginUp getRootAsUserLoginUp(ByteBuffer _bb) { return getRootAsUserLoginUp(_bb, new UserLoginUp()); }
  public static UserLoginUp getRootAsUserLoginUp(ByteBuffer _bb, UserLoginUp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public UserLoginUp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long userType() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long userId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String token() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tokenAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public String languageType() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer languageTypeAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }

  public static int createUserLoginUp(FlatBufferBuilder builder,
      long userType,
      long userId,
      int tokenOffset,
      int languageTypeOffset) {
    builder.startObject(4);
    UserLoginUp.addUserId(builder, userId);
    UserLoginUp.addUserType(builder, userType);
    UserLoginUp.addLanguageType(builder, languageTypeOffset);
    UserLoginUp.addToken(builder, tokenOffset);
    return UserLoginUp.endUserLoginUp(builder);
  }

  public static void startUserLoginUp(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addUserType(FlatBufferBuilder builder, long userType) { builder.addLong(0, userType, 0L); }
  public static void addUserId(FlatBufferBuilder builder, long userId) { builder.addLong(1, userId, 0L); }
  public static void addToken(FlatBufferBuilder builder, int tokenOffset) { builder.addOffset(2, tokenOffset, 0); }
  public static void addLanguageType(FlatBufferBuilder builder, int languageTypeOffset) { builder.addOffset(3, languageTypeOffset, 0); }
  public static int endUserLoginUp(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

