// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.im.test.net.message.flat;

public final class CommondId_Test {
  private CommondId_Test() { }
  public static final int Test1Up = 1100100;
  public static final int Test1Down = 1100101;

  public static final String[] names = { "Test1Up", "Test1Down", };

  public static String name(int e) { return names[e - Test1Up]; }
}

