// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.common.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BindingSocketUp extends Table {
  public static BindingSocketUp getRootAsBindingSocketUp(ByteBuffer _bb) { return getRootAsBindingSocketUp(_bb, new BindingSocketUp()); }
  public static BindingSocketUp getRootAsBindingSocketUp(ByteBuffer _bb, BindingSocketUp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public BindingSocketUp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String serverId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer serverIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String token() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tokenAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public long index() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createBindingSocketUp(FlatBufferBuilder builder,
      int serverIdOffset,
      int tokenOffset,
      long index) {
    builder.startObject(3);
    BindingSocketUp.addIndex(builder, index);
    BindingSocketUp.addToken(builder, tokenOffset);
    BindingSocketUp.addServerId(builder, serverIdOffset);
    return BindingSocketUp.endBindingSocketUp(builder);
  }

  public static void startBindingSocketUp(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addServerId(FlatBufferBuilder builder, int serverIdOffset) { builder.addOffset(0, serverIdOffset, 0); }
  public static void addToken(FlatBufferBuilder builder, int tokenOffset) { builder.addOffset(1, tokenOffset, 0); }
  public static void addIndex(FlatBufferBuilder builder, long index) { builder.addInt(2, (int)index, (int)0L); }
  public static int endBindingSocketUp(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

