// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.common.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BindingSocketDown extends Table {
  public static BindingSocketDown getRootAsBindingSocketDown(ByteBuffer _bb) { return getRootAsBindingSocketDown(_bb, new BindingSocketDown()); }
  public static BindingSocketDown getRootAsBindingSocketDown(ByteBuffer _bb, BindingSocketDown obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public BindingSocketDown __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startBindingSocketDown(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endBindingSocketDown(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

