// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.common.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BroadcastUp extends Table {
  public static BroadcastUp getRootAsBroadcastUp(ByteBuffer _bb) { return getRootAsBroadcastUp(_bb, new BroadcastUp()); }
  public static BroadcastUp getRootAsBroadcastUp(ByteBuffer _bb, BroadcastUp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public BroadcastUp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long broadcastType() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long commandId() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public int content(int j) { int o = __offset(8); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int contentLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public String targetUids(int j) { int o = __offset(10); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int targetUidsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }

  public static int createBroadcastUp(FlatBufferBuilder builder,
      long broadcastType,
      long commandId,
      int contentOffset,
      int targetUidsOffset) {
    builder.startObject(4);
    BroadcastUp.addTargetUids(builder, targetUidsOffset);
    BroadcastUp.addContent(builder, contentOffset);
    BroadcastUp.addCommandId(builder, commandId);
    BroadcastUp.addBroadcastType(builder, broadcastType);
    return BroadcastUp.endBroadcastUp(builder);
  }

  public static void startBroadcastUp(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addBroadcastType(FlatBufferBuilder builder, long broadcastType) { builder.addInt(0, (int)broadcastType, (int)0L); }
  public static void addCommandId(FlatBufferBuilder builder, long commandId) { builder.addInt(1, (int)commandId, (int)0L); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(2, contentOffset, 0); }
  public static int createContentVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startContentVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addTargetUids(FlatBufferBuilder builder, int targetUidsOffset) { builder.addOffset(3, targetUidsOffset, 0); }
  public static int createTargetUidsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTargetUidsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endBroadcastUp(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

