// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.common.message.flat;

public final class CommondId_Inner {
  private CommondId_Inner() { }
  public static final int BindingSocketUp = 99901;
  public static final int BindingSocketDown = 99902;
  public static final int PingCheckUp = 99903;
  public static final int BroadcastUp = 99904;

  public static final String[] names = { "BindingSocketUp", "BindingSocketDown", "PingCheckUp", "BroadcastUp", };

  public static String name(int e) { return names[e - BindingSocketUp]; }
}

