// automatically generated by the FlatBuffers compiler, do not modify

package com.elex.common.message.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PingCheckUp extends Table {
  public static PingCheckUp getRootAsPingCheckUp(ByteBuffer _bb) { return getRootAsPingCheckUp(_bb, new PingCheckUp()); }
  public static PingCheckUp getRootAsPingCheckUp(ByteBuffer _bb, PingCheckUp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public PingCheckUp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startPingCheckUp(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endPingCheckUp(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

