// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InnerProto.proto

package com.elex.common.message.proto;

public final class InnerMessage {
  private InnerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BindingSocketUpOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BindingSocketUp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *对应FunctionId
     * </pre>
     *
     * <code>string serverId = 1;</code>
     */
    java.lang.String getServerId();
    /**
     * <pre>
     *对应FunctionId
     * </pre>
     *
     * <code>string serverId = 1;</code>
     */
    com.google.protobuf.ByteString
        getServerIdBytes();

    /**
     * <pre>
     *验证码
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <pre>
     *验证码
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     *连接对应的索引
     * </pre>
     *
     * <code>uint32 index = 3;</code>
     */
    int getIndex();
  }
  /**
   * <pre>
   *网关指令 99900
   *99901绑定socket Up
   * </pre>
   *
   * Protobuf type {@code BindingSocketUp}
   */
  public  static final class BindingSocketUp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BindingSocketUp)
      BindingSocketUpOrBuilder {
    // Use BindingSocketUp.newBuilder() to construct.
    private BindingSocketUp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BindingSocketUp() {
      serverId_ = "";
      token_ = "";
      index_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BindingSocketUp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              serverId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 24: {

              index_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elex.common.message.proto.InnerMessage.internal_static_BindingSocketUp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elex.common.message.proto.InnerMessage.internal_static_BindingSocketUp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elex.common.message.proto.InnerMessage.BindingSocketUp.class, com.elex.common.message.proto.InnerMessage.BindingSocketUp.Builder.class);
    }

    /**
     * Protobuf enum {@code BindingSocketUp.MessageEnum}
     */
    public enum MessageEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *第一个值必须是0
       * </pre>
       *
       * <code>First = 0;</code>
       */
      First(0),
      /**
       * <code>CommondId = 99901;</code>
       */
      CommondId(99901),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *第一个值必须是0
       * </pre>
       *
       * <code>First = 0;</code>
       */
      public static final int First_VALUE = 0;
      /**
       * <code>CommondId = 99901;</code>
       */
      public static final int CommondId_VALUE = 99901;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageEnum valueOf(int value) {
        return forNumber(value);
      }

      public static MessageEnum forNumber(int value) {
        switch (value) {
          case 0: return First;
          case 99901: return CommondId;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageEnum>() {
              public MessageEnum findValueByNumber(int number) {
                return MessageEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.elex.common.message.proto.InnerMessage.BindingSocketUp.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageEnum[] VALUES = values();

      public static MessageEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:BindingSocketUp.MessageEnum)
    }

    public static final int SERVERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object serverId_;
    /**
     * <pre>
     *对应FunctionId
     * </pre>
     *
     * <code>string serverId = 1;</code>
     */
    public java.lang.String getServerId() {
      java.lang.Object ref = serverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *对应FunctionId
     * </pre>
     *
     * <code>string serverId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServerIdBytes() {
      java.lang.Object ref = serverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     *验证码
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *验证码
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEX_FIELD_NUMBER = 3;
    private int index_;
    /**
     * <pre>
     *连接对应的索引
     * </pre>
     *
     * <code>uint32 index = 3;</code>
     */
    public int getIndex() {
      return index_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getServerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverId_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      if (index_ != 0) {
        output.writeUInt32(3, index_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverId_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, index_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elex.common.message.proto.InnerMessage.BindingSocketUp)) {
        return super.equals(obj);
      }
      com.elex.common.message.proto.InnerMessage.BindingSocketUp other = (com.elex.common.message.proto.InnerMessage.BindingSocketUp) obj;

      boolean result = true;
      result = result && getServerId()
          .equals(other.getServerId());
      result = result && getToken()
          .equals(other.getToken());
      result = result && (getIndex()
          == other.getIndex());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elex.common.message.proto.InnerMessage.BindingSocketUp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketUp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketUp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketUp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketUp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketUp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketUp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketUp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketUp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketUp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elex.common.message.proto.InnerMessage.BindingSocketUp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *网关指令 99900
     *99901绑定socket Up
     * </pre>
     *
     * Protobuf type {@code BindingSocketUp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BindingSocketUp)
        com.elex.common.message.proto.InnerMessage.BindingSocketUpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elex.common.message.proto.InnerMessage.internal_static_BindingSocketUp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elex.common.message.proto.InnerMessage.internal_static_BindingSocketUp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elex.common.message.proto.InnerMessage.BindingSocketUp.class, com.elex.common.message.proto.InnerMessage.BindingSocketUp.Builder.class);
      }

      // Construct using com.elex.im.common.message.proto.InnerMessage.BindingSocketUp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverId_ = "";

        token_ = "";

        index_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elex.common.message.proto.InnerMessage.internal_static_BindingSocketUp_descriptor;
      }

      public com.elex.common.message.proto.InnerMessage.BindingSocketUp getDefaultInstanceForType() {
        return com.elex.common.message.proto.InnerMessage.BindingSocketUp.getDefaultInstance();
      }

      public com.elex.common.message.proto.InnerMessage.BindingSocketUp build() {
        com.elex.common.message.proto.InnerMessage.BindingSocketUp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elex.common.message.proto.InnerMessage.BindingSocketUp buildPartial() {
        com.elex.common.message.proto.InnerMessage.BindingSocketUp result = new com.elex.common.message.proto.InnerMessage.BindingSocketUp(this);
        result.serverId_ = serverId_;
        result.token_ = token_;
        result.index_ = index_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elex.common.message.proto.InnerMessage.BindingSocketUp) {
          return mergeFrom((com.elex.common.message.proto.InnerMessage.BindingSocketUp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elex.common.message.proto.InnerMessage.BindingSocketUp other) {
        if (other == com.elex.common.message.proto.InnerMessage.BindingSocketUp.getDefaultInstance()) return this;
        if (!other.getServerId().isEmpty()) {
          serverId_ = other.serverId_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elex.common.message.proto.InnerMessage.BindingSocketUp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elex.common.message.proto.InnerMessage.BindingSocketUp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object serverId_ = "";
      /**
       * <pre>
       *对应FunctionId
       * </pre>
       *
       * <code>string serverId = 1;</code>
       */
      public java.lang.String getServerId() {
        java.lang.Object ref = serverId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *对应FunctionId
       * </pre>
       *
       * <code>string serverId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServerIdBytes() {
        java.lang.Object ref = serverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *对应FunctionId
       * </pre>
       *
       * <code>string serverId = 1;</code>
       */
      public Builder setServerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对应FunctionId
       * </pre>
       *
       * <code>string serverId = 1;</code>
       */
      public Builder clearServerId() {
        
        serverId_ = getDefaultInstance().getServerId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对应FunctionId
       * </pre>
       *
       * <code>string serverId = 1;</code>
       */
      public Builder setServerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       *验证码
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *验证码
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *验证码
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *验证码
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *验证码
       * </pre>
       *
       * <code>string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private int index_ ;
      /**
       * <pre>
       *连接对应的索引
       * </pre>
       *
       * <code>uint32 index = 3;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <pre>
       *连接对应的索引
       * </pre>
       *
       * <code>uint32 index = 3;</code>
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *连接对应的索引
       * </pre>
       *
       * <code>uint32 index = 3;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BindingSocketUp)
    }

    // @@protoc_insertion_point(class_scope:BindingSocketUp)
    private static final com.elex.common.message.proto.InnerMessage.BindingSocketUp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elex.common.message.proto.InnerMessage.BindingSocketUp();
    }

    public static com.elex.common.message.proto.InnerMessage.BindingSocketUp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BindingSocketUp>
        PARSER = new com.google.protobuf.AbstractParser<BindingSocketUp>() {
      public BindingSocketUp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BindingSocketUp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BindingSocketUp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BindingSocketUp> getParserForType() {
      return PARSER;
    }

    public com.elex.common.message.proto.InnerMessage.BindingSocketUp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BindingSocketDownOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BindingSocketDown)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *99902绑定socket Down
   * </pre>
   *
   * Protobuf type {@code BindingSocketDown}
   */
  public  static final class BindingSocketDown extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BindingSocketDown)
      BindingSocketDownOrBuilder {
    // Use BindingSocketDown.newBuilder() to construct.
    private BindingSocketDown(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BindingSocketDown() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BindingSocketDown(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elex.common.message.proto.InnerMessage.internal_static_BindingSocketDown_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elex.common.message.proto.InnerMessage.internal_static_BindingSocketDown_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elex.common.message.proto.InnerMessage.BindingSocketDown.class, com.elex.common.message.proto.InnerMessage.BindingSocketDown.Builder.class);
    }

    /**
     * Protobuf enum {@code BindingSocketDown.MessageEnum}
     */
    public enum MessageEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *第一个值必须是0
       * </pre>
       *
       * <code>First = 0;</code>
       */
      First(0),
      /**
       * <code>CommondId = 99902;</code>
       */
      CommondId(99902),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *第一个值必须是0
       * </pre>
       *
       * <code>First = 0;</code>
       */
      public static final int First_VALUE = 0;
      /**
       * <code>CommondId = 99902;</code>
       */
      public static final int CommondId_VALUE = 99902;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageEnum valueOf(int value) {
        return forNumber(value);
      }

      public static MessageEnum forNumber(int value) {
        switch (value) {
          case 0: return First;
          case 99902: return CommondId;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageEnum>() {
              public MessageEnum findValueByNumber(int number) {
                return MessageEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.elex.common.message.proto.InnerMessage.BindingSocketDown.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageEnum[] VALUES = values();

      public static MessageEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:BindingSocketDown.MessageEnum)
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elex.common.message.proto.InnerMessage.BindingSocketDown)) {
        return super.equals(obj);
      }
      com.elex.common.message.proto.InnerMessage.BindingSocketDown other = (com.elex.common.message.proto.InnerMessage.BindingSocketDown) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elex.common.message.proto.InnerMessage.BindingSocketDown parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketDown parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketDown parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketDown parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketDown parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketDown parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketDown parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketDown parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketDown parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.common.message.proto.InnerMessage.BindingSocketDown parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elex.common.message.proto.InnerMessage.BindingSocketDown prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *99902绑定socket Down
     * </pre>
     *
     * Protobuf type {@code BindingSocketDown}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BindingSocketDown)
        com.elex.common.message.proto.InnerMessage.BindingSocketDownOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elex.common.message.proto.InnerMessage.internal_static_BindingSocketDown_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elex.common.message.proto.InnerMessage.internal_static_BindingSocketDown_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elex.common.message.proto.InnerMessage.BindingSocketDown.class, com.elex.common.message.proto.InnerMessage.BindingSocketDown.Builder.class);
      }

      // Construct using com.elex.im.common.message.proto.InnerMessage.BindingSocketDown.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elex.common.message.proto.InnerMessage.internal_static_BindingSocketDown_descriptor;
      }

      public com.elex.common.message.proto.InnerMessage.BindingSocketDown getDefaultInstanceForType() {
        return com.elex.common.message.proto.InnerMessage.BindingSocketDown.getDefaultInstance();
      }

      public com.elex.common.message.proto.InnerMessage.BindingSocketDown build() {
        com.elex.common.message.proto.InnerMessage.BindingSocketDown result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elex.common.message.proto.InnerMessage.BindingSocketDown buildPartial() {
        com.elex.common.message.proto.InnerMessage.BindingSocketDown result = new com.elex.common.message.proto.InnerMessage.BindingSocketDown(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elex.common.message.proto.InnerMessage.BindingSocketDown) {
          return mergeFrom((com.elex.common.message.proto.InnerMessage.BindingSocketDown)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elex.common.message.proto.InnerMessage.BindingSocketDown other) {
        if (other == com.elex.common.message.proto.InnerMessage.BindingSocketDown.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elex.common.message.proto.InnerMessage.BindingSocketDown parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elex.common.message.proto.InnerMessage.BindingSocketDown) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BindingSocketDown)
    }

    // @@protoc_insertion_point(class_scope:BindingSocketDown)
    private static final com.elex.common.message.proto.InnerMessage.BindingSocketDown DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elex.common.message.proto.InnerMessage.BindingSocketDown();
    }

    public static com.elex.common.message.proto.InnerMessage.BindingSocketDown getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BindingSocketDown>
        PARSER = new com.google.protobuf.AbstractParser<BindingSocketDown>() {
      public BindingSocketDown parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BindingSocketDown(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BindingSocketDown> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BindingSocketDown> getParserForType() {
      return PARSER;
    }

    public com.elex.common.message.proto.InnerMessage.BindingSocketDown getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PingCheckUpOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PingCheckUp)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *99903 ping指令
   * </pre>
   *
   * Protobuf type {@code PingCheckUp}
   */
  public  static final class PingCheckUp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PingCheckUp)
      PingCheckUpOrBuilder {
    // Use PingCheckUp.newBuilder() to construct.
    private PingCheckUp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PingCheckUp() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PingCheckUp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elex.common.message.proto.InnerMessage.internal_static_PingCheckUp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elex.common.message.proto.InnerMessage.internal_static_PingCheckUp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elex.common.message.proto.InnerMessage.PingCheckUp.class, com.elex.common.message.proto.InnerMessage.PingCheckUp.Builder.class);
    }

    /**
     * Protobuf enum {@code PingCheckUp.MessageEnum}
     */
    public enum MessageEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *第一个值必须是0
       * </pre>
       *
       * <code>First = 0;</code>
       */
      First(0),
      /**
       * <code>CommondId = 99903;</code>
       */
      CommondId(99903),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *第一个值必须是0
       * </pre>
       *
       * <code>First = 0;</code>
       */
      public static final int First_VALUE = 0;
      /**
       * <code>CommondId = 99903;</code>
       */
      public static final int CommondId_VALUE = 99903;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageEnum valueOf(int value) {
        return forNumber(value);
      }

      public static MessageEnum forNumber(int value) {
        switch (value) {
          case 0: return First;
          case 99903: return CommondId;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageEnum>() {
              public MessageEnum findValueByNumber(int number) {
                return MessageEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.elex.common.message.proto.InnerMessage.PingCheckUp.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageEnum[] VALUES = values();

      public static MessageEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:PingCheckUp.MessageEnum)
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elex.common.message.proto.InnerMessage.PingCheckUp)) {
        return super.equals(obj);
      }
      com.elex.common.message.proto.InnerMessage.PingCheckUp other = (com.elex.common.message.proto.InnerMessage.PingCheckUp) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elex.common.message.proto.InnerMessage.PingCheckUp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.common.message.proto.InnerMessage.PingCheckUp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.PingCheckUp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.common.message.proto.InnerMessage.PingCheckUp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.PingCheckUp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.common.message.proto.InnerMessage.PingCheckUp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.PingCheckUp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elex.common.message.proto.InnerMessage.PingCheckUp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.PingCheckUp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.common.message.proto.InnerMessage.PingCheckUp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elex.common.message.proto.InnerMessage.PingCheckUp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *99903 ping指令
     * </pre>
     *
     * Protobuf type {@code PingCheckUp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PingCheckUp)
        com.elex.common.message.proto.InnerMessage.PingCheckUpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elex.common.message.proto.InnerMessage.internal_static_PingCheckUp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elex.common.message.proto.InnerMessage.internal_static_PingCheckUp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elex.common.message.proto.InnerMessage.PingCheckUp.class, com.elex.common.message.proto.InnerMessage.PingCheckUp.Builder.class);
      }

      // Construct using com.elex.im.common.message.proto.InnerMessage.PingCheckUp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elex.common.message.proto.InnerMessage.internal_static_PingCheckUp_descriptor;
      }

      public com.elex.common.message.proto.InnerMessage.PingCheckUp getDefaultInstanceForType() {
        return com.elex.common.message.proto.InnerMessage.PingCheckUp.getDefaultInstance();
      }

      public com.elex.common.message.proto.InnerMessage.PingCheckUp build() {
        com.elex.common.message.proto.InnerMessage.PingCheckUp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elex.common.message.proto.InnerMessage.PingCheckUp buildPartial() {
        com.elex.common.message.proto.InnerMessage.PingCheckUp result = new com.elex.common.message.proto.InnerMessage.PingCheckUp(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elex.common.message.proto.InnerMessage.PingCheckUp) {
          return mergeFrom((com.elex.common.message.proto.InnerMessage.PingCheckUp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elex.common.message.proto.InnerMessage.PingCheckUp other) {
        if (other == com.elex.common.message.proto.InnerMessage.PingCheckUp.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elex.common.message.proto.InnerMessage.PingCheckUp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elex.common.message.proto.InnerMessage.PingCheckUp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PingCheckUp)
    }

    // @@protoc_insertion_point(class_scope:PingCheckUp)
    private static final com.elex.common.message.proto.InnerMessage.PingCheckUp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elex.common.message.proto.InnerMessage.PingCheckUp();
    }

    public static com.elex.common.message.proto.InnerMessage.PingCheckUp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PingCheckUp>
        PARSER = new com.google.protobuf.AbstractParser<PingCheckUp>() {
      public PingCheckUp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PingCheckUp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PingCheckUp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PingCheckUp> getParserForType() {
      return PARSER;
    }

    public com.elex.common.message.proto.InnerMessage.PingCheckUp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BroadcastUpOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BroadcastUp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *1-指定用户转发，2-全服转发
     * </pre>
     *
     * <code>uint32 broadcastType = 1;</code>
     */
    int getBroadcastType();

    /**
     * <pre>
     *指令id
     * </pre>
     *
     * <code>uint32 commandId = 2;</code>
     */
    int getCommandId();

    /**
     * <pre>
     *要转发的内容（直接封装好的proto信息）
     * </pre>
     *
     * <code>bytes content = 3;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <pre>
     *类型为1用到
     * </pre>
     *
     * <code>repeated string targetUids = 4;</code>
     */
    java.util.List<java.lang.String>
        getTargetUidsList();
    /**
     * <pre>
     *类型为1用到
     * </pre>
     *
     * <code>repeated string targetUids = 4;</code>
     */
    int getTargetUidsCount();
    /**
     * <pre>
     *类型为1用到
     * </pre>
     *
     * <code>repeated string targetUids = 4;</code>
     */
    java.lang.String getTargetUids(int index);
    /**
     * <pre>
     *类型为1用到
     * </pre>
     *
     * <code>repeated string targetUids = 4;</code>
     */
    com.google.protobuf.ByteString
        getTargetUidsBytes(int index);
  }
  /**
   * <pre>
   *99904 广播指令
   * </pre>
   *
   * Protobuf type {@code BroadcastUp}
   */
  public  static final class BroadcastUp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BroadcastUp)
      BroadcastUpOrBuilder {
    // Use BroadcastUp.newBuilder() to construct.
    private BroadcastUp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BroadcastUp() {
      broadcastType_ = 0;
      commandId_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
      targetUids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BroadcastUp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              broadcastType_ = input.readUInt32();
              break;
            }
            case 16: {

              commandId_ = input.readUInt32();
              break;
            }
            case 26: {

              content_ = input.readBytes();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                targetUids_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              targetUids_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          targetUids_ = targetUids_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elex.common.message.proto.InnerMessage.internal_static_BroadcastUp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elex.common.message.proto.InnerMessage.internal_static_BroadcastUp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elex.common.message.proto.InnerMessage.BroadcastUp.class, com.elex.common.message.proto.InnerMessage.BroadcastUp.Builder.class);
    }

    /**
     * Protobuf enum {@code BroadcastUp.MessageEnum}
     */
    public enum MessageEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *第一个值必须是0
       * </pre>
       *
       * <code>First = 0;</code>
       */
      First(0),
      /**
       * <code>CommondId = 99904;</code>
       */
      CommondId(99904),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *第一个值必须是0
       * </pre>
       *
       * <code>First = 0;</code>
       */
      public static final int First_VALUE = 0;
      /**
       * <code>CommondId = 99904;</code>
       */
      public static final int CommondId_VALUE = 99904;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageEnum valueOf(int value) {
        return forNumber(value);
      }

      public static MessageEnum forNumber(int value) {
        switch (value) {
          case 0: return First;
          case 99904: return CommondId;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageEnum>() {
              public MessageEnum findValueByNumber(int number) {
                return MessageEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.elex.common.message.proto.InnerMessage.BroadcastUp.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageEnum[] VALUES = values();

      public static MessageEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:BroadcastUp.MessageEnum)
    }

    private int bitField0_;
    public static final int BROADCASTTYPE_FIELD_NUMBER = 1;
    private int broadcastType_;
    /**
     * <pre>
     *1-指定用户转发，2-全服转发
     * </pre>
     *
     * <code>uint32 broadcastType = 1;</code>
     */
    public int getBroadcastType() {
      return broadcastType_;
    }

    public static final int COMMANDID_FIELD_NUMBER = 2;
    private int commandId_;
    /**
     * <pre>
     *指令id
     * </pre>
     *
     * <code>uint32 commandId = 2;</code>
     */
    public int getCommandId() {
      return commandId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString content_;
    /**
     * <pre>
     *要转发的内容（直接封装好的proto信息）
     * </pre>
     *
     * <code>bytes content = 3;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int TARGETUIDS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList targetUids_;
    /**
     * <pre>
     *类型为1用到
     * </pre>
     *
     * <code>repeated string targetUids = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTargetUidsList() {
      return targetUids_;
    }
    /**
     * <pre>
     *类型为1用到
     * </pre>
     *
     * <code>repeated string targetUids = 4;</code>
     */
    public int getTargetUidsCount() {
      return targetUids_.size();
    }
    /**
     * <pre>
     *类型为1用到
     * </pre>
     *
     * <code>repeated string targetUids = 4;</code>
     */
    public java.lang.String getTargetUids(int index) {
      return targetUids_.get(index);
    }
    /**
     * <pre>
     *类型为1用到
     * </pre>
     *
     * <code>repeated string targetUids = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTargetUidsBytes(int index) {
      return targetUids_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (broadcastType_ != 0) {
        output.writeUInt32(1, broadcastType_);
      }
      if (commandId_ != 0) {
        output.writeUInt32(2, commandId_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(3, content_);
      }
      for (int i = 0; i < targetUids_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, targetUids_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (broadcastType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, broadcastType_);
      }
      if (commandId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, commandId_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, content_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < targetUids_.size(); i++) {
          dataSize += computeStringSizeNoTag(targetUids_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTargetUidsList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elex.common.message.proto.InnerMessage.BroadcastUp)) {
        return super.equals(obj);
      }
      com.elex.common.message.proto.InnerMessage.BroadcastUp other = (com.elex.common.message.proto.InnerMessage.BroadcastUp) obj;

      boolean result = true;
      result = result && (getBroadcastType()
          == other.getBroadcastType());
      result = result && (getCommandId()
          == other.getCommandId());
      result = result && getContent()
          .equals(other.getContent());
      result = result && getTargetUidsList()
          .equals(other.getTargetUidsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BROADCASTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBroadcastType();
      hash = (37 * hash) + COMMANDID_FIELD_NUMBER;
      hash = (53 * hash) + getCommandId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      if (getTargetUidsCount() > 0) {
        hash = (37 * hash) + TARGETUIDS_FIELD_NUMBER;
        hash = (53 * hash) + getTargetUidsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elex.common.message.proto.InnerMessage.BroadcastUp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.common.message.proto.InnerMessage.BroadcastUp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.BroadcastUp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.common.message.proto.InnerMessage.BroadcastUp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.BroadcastUp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.common.message.proto.InnerMessage.BroadcastUp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.BroadcastUp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elex.common.message.proto.InnerMessage.BroadcastUp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.common.message.proto.InnerMessage.BroadcastUp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.common.message.proto.InnerMessage.BroadcastUp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elex.common.message.proto.InnerMessage.BroadcastUp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *99904 广播指令
     * </pre>
     *
     * Protobuf type {@code BroadcastUp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BroadcastUp)
        com.elex.common.message.proto.InnerMessage.BroadcastUpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elex.common.message.proto.InnerMessage.internal_static_BroadcastUp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elex.common.message.proto.InnerMessage.internal_static_BroadcastUp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elex.common.message.proto.InnerMessage.BroadcastUp.class, com.elex.common.message.proto.InnerMessage.BroadcastUp.Builder.class);
      }

      // Construct using com.elex.im.common.message.proto.InnerMessage.BroadcastUp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        broadcastType_ = 0;

        commandId_ = 0;

        content_ = com.google.protobuf.ByteString.EMPTY;

        targetUids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elex.common.message.proto.InnerMessage.internal_static_BroadcastUp_descriptor;
      }

      public com.elex.common.message.proto.InnerMessage.BroadcastUp getDefaultInstanceForType() {
        return com.elex.common.message.proto.InnerMessage.BroadcastUp.getDefaultInstance();
      }

      public com.elex.common.message.proto.InnerMessage.BroadcastUp build() {
        com.elex.common.message.proto.InnerMessage.BroadcastUp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elex.common.message.proto.InnerMessage.BroadcastUp buildPartial() {
        com.elex.common.message.proto.InnerMessage.BroadcastUp result = new com.elex.common.message.proto.InnerMessage.BroadcastUp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.broadcastType_ = broadcastType_;
        result.commandId_ = commandId_;
        result.content_ = content_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          targetUids_ = targetUids_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.targetUids_ = targetUids_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elex.common.message.proto.InnerMessage.BroadcastUp) {
          return mergeFrom((com.elex.common.message.proto.InnerMessage.BroadcastUp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elex.common.message.proto.InnerMessage.BroadcastUp other) {
        if (other == com.elex.common.message.proto.InnerMessage.BroadcastUp.getDefaultInstance()) return this;
        if (other.getBroadcastType() != 0) {
          setBroadcastType(other.getBroadcastType());
        }
        if (other.getCommandId() != 0) {
          setCommandId(other.getCommandId());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (!other.targetUids_.isEmpty()) {
          if (targetUids_.isEmpty()) {
            targetUids_ = other.targetUids_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTargetUidsIsMutable();
            targetUids_.addAll(other.targetUids_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elex.common.message.proto.InnerMessage.BroadcastUp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elex.common.message.proto.InnerMessage.BroadcastUp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int broadcastType_ ;
      /**
       * <pre>
       *1-指定用户转发，2-全服转发
       * </pre>
       *
       * <code>uint32 broadcastType = 1;</code>
       */
      public int getBroadcastType() {
        return broadcastType_;
      }
      /**
       * <pre>
       *1-指定用户转发，2-全服转发
       * </pre>
       *
       * <code>uint32 broadcastType = 1;</code>
       */
      public Builder setBroadcastType(int value) {
        
        broadcastType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1-指定用户转发，2-全服转发
       * </pre>
       *
       * <code>uint32 broadcastType = 1;</code>
       */
      public Builder clearBroadcastType() {
        
        broadcastType_ = 0;
        onChanged();
        return this;
      }

      private int commandId_ ;
      /**
       * <pre>
       *指令id
       * </pre>
       *
       * <code>uint32 commandId = 2;</code>
       */
      public int getCommandId() {
        return commandId_;
      }
      /**
       * <pre>
       *指令id
       * </pre>
       *
       * <code>uint32 commandId = 2;</code>
       */
      public Builder setCommandId(int value) {
        
        commandId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *指令id
       * </pre>
       *
       * <code>uint32 commandId = 2;</code>
       */
      public Builder clearCommandId() {
        
        commandId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *要转发的内容（直接封装好的proto信息）
       * </pre>
       *
       * <code>bytes content = 3;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <pre>
       *要转发的内容（直接封装好的proto信息）
       * </pre>
       *
       * <code>bytes content = 3;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *要转发的内容（直接封装好的proto信息）
       * </pre>
       *
       * <code>bytes content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList targetUids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTargetUidsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          targetUids_ = new com.google.protobuf.LazyStringArrayList(targetUids_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       *类型为1用到
       * </pre>
       *
       * <code>repeated string targetUids = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTargetUidsList() {
        return targetUids_.getUnmodifiableView();
      }
      /**
       * <pre>
       *类型为1用到
       * </pre>
       *
       * <code>repeated string targetUids = 4;</code>
       */
      public int getTargetUidsCount() {
        return targetUids_.size();
      }
      /**
       * <pre>
       *类型为1用到
       * </pre>
       *
       * <code>repeated string targetUids = 4;</code>
       */
      public java.lang.String getTargetUids(int index) {
        return targetUids_.get(index);
      }
      /**
       * <pre>
       *类型为1用到
       * </pre>
       *
       * <code>repeated string targetUids = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTargetUidsBytes(int index) {
        return targetUids_.getByteString(index);
      }
      /**
       * <pre>
       *类型为1用到
       * </pre>
       *
       * <code>repeated string targetUids = 4;</code>
       */
      public Builder setTargetUids(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetUidsIsMutable();
        targetUids_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *类型为1用到
       * </pre>
       *
       * <code>repeated string targetUids = 4;</code>
       */
      public Builder addTargetUids(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetUidsIsMutable();
        targetUids_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *类型为1用到
       * </pre>
       *
       * <code>repeated string targetUids = 4;</code>
       */
      public Builder addAllTargetUids(
          java.lang.Iterable<java.lang.String> values) {
        ensureTargetUidsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, targetUids_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *类型为1用到
       * </pre>
       *
       * <code>repeated string targetUids = 4;</code>
       */
      public Builder clearTargetUids() {
        targetUids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *类型为1用到
       * </pre>
       *
       * <code>repeated string targetUids = 4;</code>
       */
      public Builder addTargetUidsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTargetUidsIsMutable();
        targetUids_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BroadcastUp)
    }

    // @@protoc_insertion_point(class_scope:BroadcastUp)
    private static final com.elex.common.message.proto.InnerMessage.BroadcastUp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elex.common.message.proto.InnerMessage.BroadcastUp();
    }

    public static com.elex.common.message.proto.InnerMessage.BroadcastUp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BroadcastUp>
        PARSER = new com.google.protobuf.AbstractParser<BroadcastUp>() {
      public BroadcastUp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BroadcastUp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BroadcastUp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BroadcastUp> getParserForType() {
      return PARSER;
    }

    public com.elex.common.message.proto.InnerMessage.BroadcastUp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BindingSocketUp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BindingSocketUp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BindingSocketDown_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BindingSocketDown_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PingCheckUp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PingCheckUp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BroadcastUp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BroadcastUp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020InnerProto.proto\"l\n\017BindingSocketUp\022\020\n" +
      "\010serverId\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\022\r\n\005index\030" +
      "\003 \001(\r\")\n\013MessageEnum\022\t\n\005First\020\000\022\017\n\tCommo" +
      "ndId\020\275\214\006\">\n\021BindingSocketDown\")\n\013Message" +
      "Enum\022\t\n\005First\020\000\022\017\n\tCommondId\020\276\214\006\"8\n\013Ping" +
      "CheckUp\")\n\013MessageEnum\022\t\n\005First\020\000\022\017\n\tCom" +
      "mondId\020\277\214\006\"\207\001\n\013BroadcastUp\022\025\n\rbroadcastT" +
      "ype\030\001 \001(\r\022\021\n\tcommandId\030\002 \001(\r\022\017\n\007content\030" +
      "\003 \001(\014\022\022\n\ntargetUids\030\004 \003(\t\")\n\013MessageEnum" +
      "\022\t\n\005First\020\000\022\017\n\tCommondId\020\300\214\006B0\n com.elex",
      ".im.common.message.protoB\014InnerMessageb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BindingSocketUp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BindingSocketUp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BindingSocketUp_descriptor,
        new java.lang.String[] { "ServerId", "Token", "Index", });
    internal_static_BindingSocketDown_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BindingSocketDown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BindingSocketDown_descriptor,
        new java.lang.String[] { });
    internal_static_PingCheckUp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PingCheckUp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PingCheckUp_descriptor,
        new java.lang.String[] { });
    internal_static_BroadcastUp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BroadcastUp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BroadcastUp_descriptor,
        new java.lang.String[] { "BroadcastType", "CommandId", "Content", "TargetUids", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
