// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrorMessage.proto

package com.elex.im.message.proto;

public final class ErrorMessage {
  private ErrorMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ErrorMessageDownOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ErrorMessageDown)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *错误类型（0.请求参数错误; 1.数据错误; 2.系统错误）
     * </pre>
     *
     * <code>uint32 errorType = 1;</code>
     */
    int getErrorType();

    /**
     * <pre>
     *错误细节（定义常量）
     * </pre>
     *
     * <code>uint32 errorDetail = 2;</code>
     */
    int getErrorDetail();

    /**
     * <pre>
     *指令id
     * </pre>
     *
     * <code>uint32 commandId = 3;</code>
     */
    int getCommandId();
  }
  /**
   * <pre>
   *---------------------------------
   *90001 统一返回错误结果Down
   * </pre>
   *
   * Protobuf type {@code ErrorMessageDown}
   */
  public  static final class ErrorMessageDown extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ErrorMessageDown)
      ErrorMessageDownOrBuilder {
    // Use ErrorMessageDown.newBuilder() to construct.
    private ErrorMessageDown(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorMessageDown() {
      errorType_ = 0;
      errorDetail_ = 0;
      commandId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ErrorMessageDown(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              errorType_ = input.readUInt32();
              break;
            }
            case 16: {

              errorDetail_ = input.readUInt32();
              break;
            }
            case 24: {

              commandId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elex.im.message.proto.ErrorMessage.internal_static_ErrorMessageDown_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elex.im.message.proto.ErrorMessage.internal_static_ErrorMessageDown_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elex.im.message.proto.ErrorMessage.ErrorMessageDown.class, com.elex.im.message.proto.ErrorMessage.ErrorMessageDown.Builder.class);
    }

    /**
     * Protobuf enum {@code ErrorMessageDown.MessageEnum}
     */
    public enum MessageEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>First = 0;</code>
       */
      First(0),
      /**
       * <code>CommondId = 90001;</code>
       */
      CommondId(90001),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>First = 0;</code>
       */
      public static final int First_VALUE = 0;
      /**
       * <code>CommondId = 90001;</code>
       */
      public static final int CommondId_VALUE = 90001;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageEnum valueOf(int value) {
        return forNumber(value);
      }

      public static MessageEnum forNumber(int value) {
        switch (value) {
          case 0: return First;
          case 90001: return CommondId;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageEnum>() {
              public MessageEnum findValueByNumber(int number) {
                return MessageEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.elex.im.message.proto.ErrorMessage.ErrorMessageDown.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageEnum[] VALUES = values();

      public static MessageEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ErrorMessageDown.MessageEnum)
    }

    public static final int ERRORTYPE_FIELD_NUMBER = 1;
    private int errorType_;
    /**
     * <pre>
     *错误类型（0.请求参数错误; 1.数据错误; 2.系统错误）
     * </pre>
     *
     * <code>uint32 errorType = 1;</code>
     */
    public int getErrorType() {
      return errorType_;
    }

    public static final int ERRORDETAIL_FIELD_NUMBER = 2;
    private int errorDetail_;
    /**
     * <pre>
     *错误细节（定义常量）
     * </pre>
     *
     * <code>uint32 errorDetail = 2;</code>
     */
    public int getErrorDetail() {
      return errorDetail_;
    }

    public static final int COMMANDID_FIELD_NUMBER = 3;
    private int commandId_;
    /**
     * <pre>
     *指令id
     * </pre>
     *
     * <code>uint32 commandId = 3;</code>
     */
    public int getCommandId() {
      return commandId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorType_ != 0) {
        output.writeUInt32(1, errorType_);
      }
      if (errorDetail_ != 0) {
        output.writeUInt32(2, errorDetail_);
      }
      if (commandId_ != 0) {
        output.writeUInt32(3, commandId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, errorType_);
      }
      if (errorDetail_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, errorDetail_);
      }
      if (commandId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, commandId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elex.im.message.proto.ErrorMessage.ErrorMessageDown)) {
        return super.equals(obj);
      }
      com.elex.im.message.proto.ErrorMessage.ErrorMessageDown other = (com.elex.im.message.proto.ErrorMessage.ErrorMessageDown) obj;

      boolean result = true;
      result = result && (getErrorType()
          == other.getErrorType());
      result = result && (getErrorDetail()
          == other.getErrorDetail());
      result = result && (getCommandId()
          == other.getCommandId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorType();
      hash = (37 * hash) + ERRORDETAIL_FIELD_NUMBER;
      hash = (53 * hash) + getErrorDetail();
      hash = (37 * hash) + COMMANDID_FIELD_NUMBER;
      hash = (53 * hash) + getCommandId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elex.im.message.proto.ErrorMessage.ErrorMessageDown parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.im.message.proto.ErrorMessage.ErrorMessageDown parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.im.message.proto.ErrorMessage.ErrorMessageDown parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.im.message.proto.ErrorMessage.ErrorMessageDown parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.im.message.proto.ErrorMessage.ErrorMessageDown parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.im.message.proto.ErrorMessage.ErrorMessageDown parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.im.message.proto.ErrorMessage.ErrorMessageDown parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elex.im.message.proto.ErrorMessage.ErrorMessageDown parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.im.message.proto.ErrorMessage.ErrorMessageDown parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.im.message.proto.ErrorMessage.ErrorMessageDown parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elex.im.message.proto.ErrorMessage.ErrorMessageDown prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *---------------------------------
     *90001 统一返回错误结果Down
     * </pre>
     *
     * Protobuf type {@code ErrorMessageDown}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ErrorMessageDown)
        com.elex.im.message.proto.ErrorMessage.ErrorMessageDownOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elex.im.message.proto.ErrorMessage.internal_static_ErrorMessageDown_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elex.im.message.proto.ErrorMessage.internal_static_ErrorMessageDown_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elex.im.message.proto.ErrorMessage.ErrorMessageDown.class, com.elex.im.message.proto.ErrorMessage.ErrorMessageDown.Builder.class);
      }

      // Construct using com.elex.im.message.proto.ErrorMessage.ErrorMessageDown.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errorType_ = 0;

        errorDetail_ = 0;

        commandId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elex.im.message.proto.ErrorMessage.internal_static_ErrorMessageDown_descriptor;
      }

      public com.elex.im.message.proto.ErrorMessage.ErrorMessageDown getDefaultInstanceForType() {
        return com.elex.im.message.proto.ErrorMessage.ErrorMessageDown.getDefaultInstance();
      }

      public com.elex.im.message.proto.ErrorMessage.ErrorMessageDown build() {
        com.elex.im.message.proto.ErrorMessage.ErrorMessageDown result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elex.im.message.proto.ErrorMessage.ErrorMessageDown buildPartial() {
        com.elex.im.message.proto.ErrorMessage.ErrorMessageDown result = new com.elex.im.message.proto.ErrorMessage.ErrorMessageDown(this);
        result.errorType_ = errorType_;
        result.errorDetail_ = errorDetail_;
        result.commandId_ = commandId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elex.im.message.proto.ErrorMessage.ErrorMessageDown) {
          return mergeFrom((com.elex.im.message.proto.ErrorMessage.ErrorMessageDown)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elex.im.message.proto.ErrorMessage.ErrorMessageDown other) {
        if (other == com.elex.im.message.proto.ErrorMessage.ErrorMessageDown.getDefaultInstance()) return this;
        if (other.getErrorType() != 0) {
          setErrorType(other.getErrorType());
        }
        if (other.getErrorDetail() != 0) {
          setErrorDetail(other.getErrorDetail());
        }
        if (other.getCommandId() != 0) {
          setCommandId(other.getCommandId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elex.im.message.proto.ErrorMessage.ErrorMessageDown parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elex.im.message.proto.ErrorMessage.ErrorMessageDown) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errorType_ ;
      /**
       * <pre>
       *错误类型（0.请求参数错误; 1.数据错误; 2.系统错误）
       * </pre>
       *
       * <code>uint32 errorType = 1;</code>
       */
      public int getErrorType() {
        return errorType_;
      }
      /**
       * <pre>
       *错误类型（0.请求参数错误; 1.数据错误; 2.系统错误）
       * </pre>
       *
       * <code>uint32 errorType = 1;</code>
       */
      public Builder setErrorType(int value) {
        
        errorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误类型（0.请求参数错误; 1.数据错误; 2.系统错误）
       * </pre>
       *
       * <code>uint32 errorType = 1;</code>
       */
      public Builder clearErrorType() {
        
        errorType_ = 0;
        onChanged();
        return this;
      }

      private int errorDetail_ ;
      /**
       * <pre>
       *错误细节（定义常量）
       * </pre>
       *
       * <code>uint32 errorDetail = 2;</code>
       */
      public int getErrorDetail() {
        return errorDetail_;
      }
      /**
       * <pre>
       *错误细节（定义常量）
       * </pre>
       *
       * <code>uint32 errorDetail = 2;</code>
       */
      public Builder setErrorDetail(int value) {
        
        errorDetail_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误细节（定义常量）
       * </pre>
       *
       * <code>uint32 errorDetail = 2;</code>
       */
      public Builder clearErrorDetail() {
        
        errorDetail_ = 0;
        onChanged();
        return this;
      }

      private int commandId_ ;
      /**
       * <pre>
       *指令id
       * </pre>
       *
       * <code>uint32 commandId = 3;</code>
       */
      public int getCommandId() {
        return commandId_;
      }
      /**
       * <pre>
       *指令id
       * </pre>
       *
       * <code>uint32 commandId = 3;</code>
       */
      public Builder setCommandId(int value) {
        
        commandId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *指令id
       * </pre>
       *
       * <code>uint32 commandId = 3;</code>
       */
      public Builder clearCommandId() {
        
        commandId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ErrorMessageDown)
    }

    // @@protoc_insertion_point(class_scope:ErrorMessageDown)
    private static final com.elex.im.message.proto.ErrorMessage.ErrorMessageDown DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elex.im.message.proto.ErrorMessage.ErrorMessageDown();
    }

    public static com.elex.im.message.proto.ErrorMessage.ErrorMessageDown getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorMessageDown>
        PARSER = new com.google.protobuf.AbstractParser<ErrorMessageDown>() {
      public ErrorMessageDown parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ErrorMessageDown(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ErrorMessageDown> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorMessageDown> getParserForType() {
      return PARSER;
    }

    public com.elex.im.message.proto.ErrorMessage.ErrorMessageDown getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SuccessMessageDownOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SuccessMessageDown)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *指令id
     * </pre>
     *
     * <code>uint32 commandId = 1;</code>
     */
    int getCommandId();
  }
  /**
   * <pre>
   *90002 统一返回成功结果Down
   * </pre>
   *
   * Protobuf type {@code SuccessMessageDown}
   */
  public  static final class SuccessMessageDown extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SuccessMessageDown)
      SuccessMessageDownOrBuilder {
    // Use SuccessMessageDown.newBuilder() to construct.
    private SuccessMessageDown(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SuccessMessageDown() {
      commandId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SuccessMessageDown(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              commandId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elex.im.message.proto.ErrorMessage.internal_static_SuccessMessageDown_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elex.im.message.proto.ErrorMessage.internal_static_SuccessMessageDown_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elex.im.message.proto.ErrorMessage.SuccessMessageDown.class, com.elex.im.message.proto.ErrorMessage.SuccessMessageDown.Builder.class);
    }

    /**
     * Protobuf enum {@code SuccessMessageDown.MessageEnum}
     */
    public enum MessageEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>First = 0;</code>
       */
      First(0),
      /**
       * <code>CommondId = 90002;</code>
       */
      CommondId(90002),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>First = 0;</code>
       */
      public static final int First_VALUE = 0;
      /**
       * <code>CommondId = 90002;</code>
       */
      public static final int CommondId_VALUE = 90002;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageEnum valueOf(int value) {
        return forNumber(value);
      }

      public static MessageEnum forNumber(int value) {
        switch (value) {
          case 0: return First;
          case 90002: return CommondId;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageEnum>() {
              public MessageEnum findValueByNumber(int number) {
                return MessageEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.elex.im.message.proto.ErrorMessage.SuccessMessageDown.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageEnum[] VALUES = values();

      public static MessageEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SuccessMessageDown.MessageEnum)
    }

    public static final int COMMANDID_FIELD_NUMBER = 1;
    private int commandId_;
    /**
     * <pre>
     *指令id
     * </pre>
     *
     * <code>uint32 commandId = 1;</code>
     */
    public int getCommandId() {
      return commandId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commandId_ != 0) {
        output.writeUInt32(1, commandId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commandId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, commandId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elex.im.message.proto.ErrorMessage.SuccessMessageDown)) {
        return super.equals(obj);
      }
      com.elex.im.message.proto.ErrorMessage.SuccessMessageDown other = (com.elex.im.message.proto.ErrorMessage.SuccessMessageDown) obj;

      boolean result = true;
      result = result && (getCommandId()
          == other.getCommandId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMANDID_FIELD_NUMBER;
      hash = (53 * hash) + getCommandId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elex.im.message.proto.ErrorMessage.SuccessMessageDown parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.im.message.proto.ErrorMessage.SuccessMessageDown parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.im.message.proto.ErrorMessage.SuccessMessageDown parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.im.message.proto.ErrorMessage.SuccessMessageDown parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.im.message.proto.ErrorMessage.SuccessMessageDown parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.im.message.proto.ErrorMessage.SuccessMessageDown parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.im.message.proto.ErrorMessage.SuccessMessageDown parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elex.im.message.proto.ErrorMessage.SuccessMessageDown parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.im.message.proto.ErrorMessage.SuccessMessageDown parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.im.message.proto.ErrorMessage.SuccessMessageDown parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elex.im.message.proto.ErrorMessage.SuccessMessageDown prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *90002 统一返回成功结果Down
     * </pre>
     *
     * Protobuf type {@code SuccessMessageDown}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SuccessMessageDown)
        com.elex.im.message.proto.ErrorMessage.SuccessMessageDownOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elex.im.message.proto.ErrorMessage.internal_static_SuccessMessageDown_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elex.im.message.proto.ErrorMessage.internal_static_SuccessMessageDown_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elex.im.message.proto.ErrorMessage.SuccessMessageDown.class, com.elex.im.message.proto.ErrorMessage.SuccessMessageDown.Builder.class);
      }

      // Construct using com.elex.im.message.proto.ErrorMessage.SuccessMessageDown.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        commandId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elex.im.message.proto.ErrorMessage.internal_static_SuccessMessageDown_descriptor;
      }

      public com.elex.im.message.proto.ErrorMessage.SuccessMessageDown getDefaultInstanceForType() {
        return com.elex.im.message.proto.ErrorMessage.SuccessMessageDown.getDefaultInstance();
      }

      public com.elex.im.message.proto.ErrorMessage.SuccessMessageDown build() {
        com.elex.im.message.proto.ErrorMessage.SuccessMessageDown result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elex.im.message.proto.ErrorMessage.SuccessMessageDown buildPartial() {
        com.elex.im.message.proto.ErrorMessage.SuccessMessageDown result = new com.elex.im.message.proto.ErrorMessage.SuccessMessageDown(this);
        result.commandId_ = commandId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elex.im.message.proto.ErrorMessage.SuccessMessageDown) {
          return mergeFrom((com.elex.im.message.proto.ErrorMessage.SuccessMessageDown)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elex.im.message.proto.ErrorMessage.SuccessMessageDown other) {
        if (other == com.elex.im.message.proto.ErrorMessage.SuccessMessageDown.getDefaultInstance()) return this;
        if (other.getCommandId() != 0) {
          setCommandId(other.getCommandId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elex.im.message.proto.ErrorMessage.SuccessMessageDown parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elex.im.message.proto.ErrorMessage.SuccessMessageDown) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int commandId_ ;
      /**
       * <pre>
       *指令id
       * </pre>
       *
       * <code>uint32 commandId = 1;</code>
       */
      public int getCommandId() {
        return commandId_;
      }
      /**
       * <pre>
       *指令id
       * </pre>
       *
       * <code>uint32 commandId = 1;</code>
       */
      public Builder setCommandId(int value) {
        
        commandId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *指令id
       * </pre>
       *
       * <code>uint32 commandId = 1;</code>
       */
      public Builder clearCommandId() {
        
        commandId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SuccessMessageDown)
    }

    // @@protoc_insertion_point(class_scope:SuccessMessageDown)
    private static final com.elex.im.message.proto.ErrorMessage.SuccessMessageDown DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elex.im.message.proto.ErrorMessage.SuccessMessageDown();
    }

    public static com.elex.im.message.proto.ErrorMessage.SuccessMessageDown getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SuccessMessageDown>
        PARSER = new com.google.protobuf.AbstractParser<SuccessMessageDown>() {
      public SuccessMessageDown parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SuccessMessageDown(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SuccessMessageDown> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SuccessMessageDown> getParserForType() {
      return PARSER;
    }

    public com.elex.im.message.proto.ErrorMessage.SuccessMessageDown getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrorMessageDown_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrorMessageDown_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SuccessMessageDown_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SuccessMessageDown_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ErrorMessage.proto\"x\n\020ErrorMessageDown" +
      "\022\021\n\terrorType\030\001 \001(\r\022\023\n\013errorDetail\030\002 \001(\r" +
      "\022\021\n\tcommandId\030\003 \001(\r\")\n\013MessageEnum\022\t\n\005Fi" +
      "rst\020\000\022\017\n\tCommondId\020\221\277\005\"R\n\022SuccessMessage" +
      "Down\022\021\n\tcommandId\030\001 \001(\r\")\n\013MessageEnum\022\t" +
      "\n\005First\020\000\022\017\n\tCommondId\020\222\277\005B)\n\031com.elex.i" +
      "m.message.protoB\014ErrorMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ErrorMessageDown_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ErrorMessageDown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrorMessageDown_descriptor,
        new java.lang.String[] { "ErrorType", "ErrorDetail", "CommandId", });
    internal_static_SuccessMessageDown_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SuccessMessageDown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SuccessMessageDown_descriptor,
        new java.lang.String[] { "CommandId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
