// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/1100100_Test1Message.proto

package com.elex.im.test.net.message.proto;

public final class Test1Message {
  private Test1Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Test1BeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Test1Bean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     *区id
     * </pre>
     *
     * <code>uint32 rid = 2;</code>
     */
    int getRid();

    /**
     * <pre>
     *登陆的用户id
     * </pre>
     *
     * <code>string userIdStr = 3;</code>
     */
    java.lang.String getUserIdStr();
    /**
     * <pre>
     *登陆的用户id
     * </pre>
     *
     * <code>string userIdStr = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserIdStrBytes();

    /**
     * <pre>
     *验证服id
     * </pre>
     *
     * <code>uint32 asid = 4;</code>
     */
    int getAsid();
  }
  /**
   * Protobuf type {@code Test1Bean}
   */
  public  static final class Test1Bean extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Test1Bean)
      Test1BeanOrBuilder {
    // Use Test1Bean.newBuilder() to construct.
    private Test1Bean(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Test1Bean() {
      token_ = "";
      rid_ = 0;
      userIdStr_ = "";
      asid_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Test1Bean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 16: {

              rid_ = input.readUInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userIdStr_ = s;
              break;
            }
            case 32: {

              asid_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Bean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Bean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elex.im.test.net.message.proto.Test1Message.Test1Bean.class, com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder.class);
    }

    public static final int TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RID_FIELD_NUMBER = 2;
    private int rid_;
    /**
     * <pre>
     *区id
     * </pre>
     *
     * <code>uint32 rid = 2;</code>
     */
    public int getRid() {
      return rid_;
    }

    public static final int USERIDSTR_FIELD_NUMBER = 3;
    private volatile java.lang.Object userIdStr_;
    /**
     * <pre>
     *登陆的用户id
     * </pre>
     *
     * <code>string userIdStr = 3;</code>
     */
    public java.lang.String getUserIdStr() {
      java.lang.Object ref = userIdStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdStr_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *登陆的用户id
     * </pre>
     *
     * <code>string userIdStr = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdStrBytes() {
      java.lang.Object ref = userIdStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASID_FIELD_NUMBER = 4;
    private int asid_;
    /**
     * <pre>
     *验证服id
     * </pre>
     *
     * <code>uint32 asid = 4;</code>
     */
    public int getAsid() {
      return asid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
      }
      if (rid_ != 0) {
        output.writeUInt32(2, rid_);
      }
      if (!getUserIdStrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userIdStr_);
      }
      if (asid_ != 0) {
        output.writeUInt32(4, asid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
      }
      if (rid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, rid_);
      }
      if (!getUserIdStrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userIdStr_);
      }
      if (asid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, asid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elex.im.test.net.message.proto.Test1Message.Test1Bean)) {
        return super.equals(obj);
      }
      com.elex.im.test.net.message.proto.Test1Message.Test1Bean other = (com.elex.im.test.net.message.proto.Test1Message.Test1Bean) obj;

      boolean result = true;
      result = result && getToken()
          .equals(other.getToken());
      result = result && (getRid()
          == other.getRid());
      result = result && getUserIdStr()
          .equals(other.getUserIdStr());
      result = result && (getAsid()
          == other.getAsid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + RID_FIELD_NUMBER;
      hash = (53 * hash) + getRid();
      hash = (37 * hash) + USERIDSTR_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdStr().hashCode();
      hash = (37 * hash) + ASID_FIELD_NUMBER;
      hash = (53 * hash) + getAsid();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elex.im.test.net.message.proto.Test1Message.Test1Bean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Bean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Bean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Bean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Bean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Bean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Bean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Bean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Bean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Bean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elex.im.test.net.message.proto.Test1Message.Test1Bean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Test1Bean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Test1Bean)
        com.elex.im.test.net.message.proto.Test1Message.Test1BeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Bean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Bean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elex.im.test.net.message.proto.Test1Message.Test1Bean.class, com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder.class);
      }

      // Construct using com.elex.im.test.net.message.proto.Test1Message.Test1Bean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        token_ = "";

        rid_ = 0;

        userIdStr_ = "";

        asid_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Bean_descriptor;
      }

      public com.elex.im.test.net.message.proto.Test1Message.Test1Bean getDefaultInstanceForType() {
        return com.elex.im.test.net.message.proto.Test1Message.Test1Bean.getDefaultInstance();
      }

      public com.elex.im.test.net.message.proto.Test1Message.Test1Bean build() {
        com.elex.im.test.net.message.proto.Test1Message.Test1Bean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elex.im.test.net.message.proto.Test1Message.Test1Bean buildPartial() {
        com.elex.im.test.net.message.proto.Test1Message.Test1Bean result = new com.elex.im.test.net.message.proto.Test1Message.Test1Bean(this);
        result.token_ = token_;
        result.rid_ = rid_;
        result.userIdStr_ = userIdStr_;
        result.asid_ = asid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elex.im.test.net.message.proto.Test1Message.Test1Bean) {
          return mergeFrom((com.elex.im.test.net.message.proto.Test1Message.Test1Bean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elex.im.test.net.message.proto.Test1Message.Test1Bean other) {
        if (other == com.elex.im.test.net.message.proto.Test1Message.Test1Bean.getDefaultInstance()) return this;
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getRid() != 0) {
          setRid(other.getRid());
        }
        if (!other.getUserIdStr().isEmpty()) {
          userIdStr_ = other.userIdStr_;
          onChanged();
        }
        if (other.getAsid() != 0) {
          setAsid(other.getAsid());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elex.im.test.net.message.proto.Test1Message.Test1Bean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elex.im.test.net.message.proto.Test1Message.Test1Bean) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>string token = 1;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private int rid_ ;
      /**
       * <pre>
       *区id
       * </pre>
       *
       * <code>uint32 rid = 2;</code>
       */
      public int getRid() {
        return rid_;
      }
      /**
       * <pre>
       *区id
       * </pre>
       *
       * <code>uint32 rid = 2;</code>
       */
      public Builder setRid(int value) {
        
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *区id
       * </pre>
       *
       * <code>uint32 rid = 2;</code>
       */
      public Builder clearRid() {
        
        rid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userIdStr_ = "";
      /**
       * <pre>
       *登陆的用户id
       * </pre>
       *
       * <code>string userIdStr = 3;</code>
       */
      public java.lang.String getUserIdStr() {
        java.lang.Object ref = userIdStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIdStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *登陆的用户id
       * </pre>
       *
       * <code>string userIdStr = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdStrBytes() {
        java.lang.Object ref = userIdStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIdStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *登陆的用户id
       * </pre>
       *
       * <code>string userIdStr = 3;</code>
       */
      public Builder setUserIdStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *登陆的用户id
       * </pre>
       *
       * <code>string userIdStr = 3;</code>
       */
      public Builder clearUserIdStr() {
        
        userIdStr_ = getDefaultInstance().getUserIdStr();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *登陆的用户id
       * </pre>
       *
       * <code>string userIdStr = 3;</code>
       */
      public Builder setUserIdStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdStr_ = value;
        onChanged();
        return this;
      }

      private int asid_ ;
      /**
       * <pre>
       *验证服id
       * </pre>
       *
       * <code>uint32 asid = 4;</code>
       */
      public int getAsid() {
        return asid_;
      }
      /**
       * <pre>
       *验证服id
       * </pre>
       *
       * <code>uint32 asid = 4;</code>
       */
      public Builder setAsid(int value) {
        
        asid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *验证服id
       * </pre>
       *
       * <code>uint32 asid = 4;</code>
       */
      public Builder clearAsid() {
        
        asid_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Test1Bean)
    }

    // @@protoc_insertion_point(class_scope:Test1Bean)
    private static final com.elex.im.test.net.message.proto.Test1Message.Test1Bean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elex.im.test.net.message.proto.Test1Message.Test1Bean();
    }

    public static com.elex.im.test.net.message.proto.Test1Message.Test1Bean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Test1Bean>
        PARSER = new com.google.protobuf.AbstractParser<Test1Bean>() {
      public Test1Bean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Test1Bean(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Test1Bean> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Test1Bean> getParserForType() {
      return PARSER;
    }

    public com.elex.im.test.net.message.proto.Test1Message.Test1Bean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Test1UpOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Test1Up)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *测试bean
     * </pre>
     *
     * <code>.Test1Bean testBean = 1;</code>
     */
    boolean hasTestBean();
    /**
     * <pre>
     *测试bean
     * </pre>
     *
     * <code>.Test1Bean testBean = 1;</code>
     */
    com.elex.im.test.net.message.proto.Test1Message.Test1Bean getTestBean();
    /**
     * <pre>
     *测试bean
     * </pre>
     *
     * <code>.Test1Bean testBean = 1;</code>
     */
    com.elex.im.test.net.message.proto.Test1Message.Test1BeanOrBuilder getTestBeanOrBuilder();
  }
  /**
   * <pre>
   *-----------------------------
   * </pre>
   *
   * Protobuf type {@code Test1Up}
   */
  public  static final class Test1Up extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Test1Up)
      Test1UpOrBuilder {
    // Use Test1Up.newBuilder() to construct.
    private Test1Up(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Test1Up() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Test1Up(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder subBuilder = null;
              if (testBean_ != null) {
                subBuilder = testBean_.toBuilder();
              }
              testBean_ = input.readMessage(com.elex.im.test.net.message.proto.Test1Message.Test1Bean.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(testBean_);
                testBean_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Up_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Up_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elex.im.test.net.message.proto.Test1Message.Test1Up.class, com.elex.im.test.net.message.proto.Test1Message.Test1Up.Builder.class);
    }

    /**
     * Protobuf enum {@code Test1Up.MessageEnum}
     */
    public enum MessageEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *第一个值必须是0
       * </pre>
       *
       * <code>First = 0;</code>
       */
      First(0),
      /**
       * <pre>
       *指令
       * </pre>
       *
       * <code>CommondId = 1100100;</code>
       */
      CommondId(1100100),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *第一个值必须是0
       * </pre>
       *
       * <code>First = 0;</code>
       */
      public static final int First_VALUE = 0;
      /**
       * <pre>
       *指令
       * </pre>
       *
       * <code>CommondId = 1100100;</code>
       */
      public static final int CommondId_VALUE = 1100100;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageEnum valueOf(int value) {
        return forNumber(value);
      }

      public static MessageEnum forNumber(int value) {
        switch (value) {
          case 0: return First;
          case 1100100: return CommondId;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageEnum>() {
              public MessageEnum findValueByNumber(int number) {
                return MessageEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.elex.im.test.net.message.proto.Test1Message.Test1Up.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageEnum[] VALUES = values();

      public static MessageEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Test1Up.MessageEnum)
    }

    public static final int TESTBEAN_FIELD_NUMBER = 1;
    private com.elex.im.test.net.message.proto.Test1Message.Test1Bean testBean_;
    /**
     * <pre>
     *测试bean
     * </pre>
     *
     * <code>.Test1Bean testBean = 1;</code>
     */
    public boolean hasTestBean() {
      return testBean_ != null;
    }
    /**
     * <pre>
     *测试bean
     * </pre>
     *
     * <code>.Test1Bean testBean = 1;</code>
     */
    public com.elex.im.test.net.message.proto.Test1Message.Test1Bean getTestBean() {
      return testBean_ == null ? com.elex.im.test.net.message.proto.Test1Message.Test1Bean.getDefaultInstance() : testBean_;
    }
    /**
     * <pre>
     *测试bean
     * </pre>
     *
     * <code>.Test1Bean testBean = 1;</code>
     */
    public com.elex.im.test.net.message.proto.Test1Message.Test1BeanOrBuilder getTestBeanOrBuilder() {
      return getTestBean();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (testBean_ != null) {
        output.writeMessage(1, getTestBean());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (testBean_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTestBean());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elex.im.test.net.message.proto.Test1Message.Test1Up)) {
        return super.equals(obj);
      }
      com.elex.im.test.net.message.proto.Test1Message.Test1Up other = (com.elex.im.test.net.message.proto.Test1Message.Test1Up) obj;

      boolean result = true;
      result = result && (hasTestBean() == other.hasTestBean());
      if (hasTestBean()) {
        result = result && getTestBean()
            .equals(other.getTestBean());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTestBean()) {
        hash = (37 * hash) + TESTBEAN_FIELD_NUMBER;
        hash = (53 * hash) + getTestBean().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elex.im.test.net.message.proto.Test1Message.Test1Up parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Up parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Up parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Up parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Up parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Up parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Up parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Up parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Up parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Up parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elex.im.test.net.message.proto.Test1Message.Test1Up prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *-----------------------------
     * </pre>
     *
     * Protobuf type {@code Test1Up}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Test1Up)
        com.elex.im.test.net.message.proto.Test1Message.Test1UpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Up_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Up_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elex.im.test.net.message.proto.Test1Message.Test1Up.class, com.elex.im.test.net.message.proto.Test1Message.Test1Up.Builder.class);
      }

      // Construct using com.elex.im.test.net.message.proto.Test1Message.Test1Up.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (testBeanBuilder_ == null) {
          testBean_ = null;
        } else {
          testBean_ = null;
          testBeanBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Up_descriptor;
      }

      public com.elex.im.test.net.message.proto.Test1Message.Test1Up getDefaultInstanceForType() {
        return com.elex.im.test.net.message.proto.Test1Message.Test1Up.getDefaultInstance();
      }

      public com.elex.im.test.net.message.proto.Test1Message.Test1Up build() {
        com.elex.im.test.net.message.proto.Test1Message.Test1Up result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elex.im.test.net.message.proto.Test1Message.Test1Up buildPartial() {
        com.elex.im.test.net.message.proto.Test1Message.Test1Up result = new com.elex.im.test.net.message.proto.Test1Message.Test1Up(this);
        if (testBeanBuilder_ == null) {
          result.testBean_ = testBean_;
        } else {
          result.testBean_ = testBeanBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elex.im.test.net.message.proto.Test1Message.Test1Up) {
          return mergeFrom((com.elex.im.test.net.message.proto.Test1Message.Test1Up)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elex.im.test.net.message.proto.Test1Message.Test1Up other) {
        if (other == com.elex.im.test.net.message.proto.Test1Message.Test1Up.getDefaultInstance()) return this;
        if (other.hasTestBean()) {
          mergeTestBean(other.getTestBean());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elex.im.test.net.message.proto.Test1Message.Test1Up parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elex.im.test.net.message.proto.Test1Message.Test1Up) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.elex.im.test.net.message.proto.Test1Message.Test1Bean testBean_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.elex.im.test.net.message.proto.Test1Message.Test1Bean, com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder, com.elex.im.test.net.message.proto.Test1Message.Test1BeanOrBuilder> testBeanBuilder_;
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public boolean hasTestBean() {
        return testBeanBuilder_ != null || testBean_ != null;
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public com.elex.im.test.net.message.proto.Test1Message.Test1Bean getTestBean() {
        if (testBeanBuilder_ == null) {
          return testBean_ == null ? com.elex.im.test.net.message.proto.Test1Message.Test1Bean.getDefaultInstance() : testBean_;
        } else {
          return testBeanBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public Builder setTestBean(com.elex.im.test.net.message.proto.Test1Message.Test1Bean value) {
        if (testBeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          testBean_ = value;
          onChanged();
        } else {
          testBeanBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public Builder setTestBean(
          com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder builderForValue) {
        if (testBeanBuilder_ == null) {
          testBean_ = builderForValue.build();
          onChanged();
        } else {
          testBeanBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public Builder mergeTestBean(com.elex.im.test.net.message.proto.Test1Message.Test1Bean value) {
        if (testBeanBuilder_ == null) {
          if (testBean_ != null) {
            testBean_ =
              com.elex.im.test.net.message.proto.Test1Message.Test1Bean.newBuilder(testBean_).mergeFrom(value).buildPartial();
          } else {
            testBean_ = value;
          }
          onChanged();
        } else {
          testBeanBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public Builder clearTestBean() {
        if (testBeanBuilder_ == null) {
          testBean_ = null;
          onChanged();
        } else {
          testBean_ = null;
          testBeanBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder getTestBeanBuilder() {
        
        onChanged();
        return getTestBeanFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public com.elex.im.test.net.message.proto.Test1Message.Test1BeanOrBuilder getTestBeanOrBuilder() {
        if (testBeanBuilder_ != null) {
          return testBeanBuilder_.getMessageOrBuilder();
        } else {
          return testBean_ == null ?
              com.elex.im.test.net.message.proto.Test1Message.Test1Bean.getDefaultInstance() : testBean_;
        }
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.elex.im.test.net.message.proto.Test1Message.Test1Bean, com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder, com.elex.im.test.net.message.proto.Test1Message.Test1BeanOrBuilder> 
          getTestBeanFieldBuilder() {
        if (testBeanBuilder_ == null) {
          testBeanBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.elex.im.test.net.message.proto.Test1Message.Test1Bean, com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder, com.elex.im.test.net.message.proto.Test1Message.Test1BeanOrBuilder>(
                  getTestBean(),
                  getParentForChildren(),
                  isClean());
          testBean_ = null;
        }
        return testBeanBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Test1Up)
    }

    // @@protoc_insertion_point(class_scope:Test1Up)
    private static final com.elex.im.test.net.message.proto.Test1Message.Test1Up DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elex.im.test.net.message.proto.Test1Message.Test1Up();
    }

    public static com.elex.im.test.net.message.proto.Test1Message.Test1Up getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Test1Up>
        PARSER = new com.google.protobuf.AbstractParser<Test1Up>() {
      public Test1Up parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Test1Up(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Test1Up> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Test1Up> getParserForType() {
      return PARSER;
    }

    public com.elex.im.test.net.message.proto.Test1Message.Test1Up getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Test1DownOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Test1Down)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *测试bean
     * </pre>
     *
     * <code>.Test1Bean testBean = 1;</code>
     */
    boolean hasTestBean();
    /**
     * <pre>
     *测试bean
     * </pre>
     *
     * <code>.Test1Bean testBean = 1;</code>
     */
    com.elex.im.test.net.message.proto.Test1Message.Test1Bean getTestBean();
    /**
     * <pre>
     *测试bean
     * </pre>
     *
     * <code>.Test1Bean testBean = 1;</code>
     */
    com.elex.im.test.net.message.proto.Test1Message.Test1BeanOrBuilder getTestBeanOrBuilder();
  }
  /**
   * Protobuf type {@code Test1Down}
   */
  public  static final class Test1Down extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Test1Down)
      Test1DownOrBuilder {
    // Use Test1Down.newBuilder() to construct.
    private Test1Down(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Test1Down() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Test1Down(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder subBuilder = null;
              if (testBean_ != null) {
                subBuilder = testBean_.toBuilder();
              }
              testBean_ = input.readMessage(com.elex.im.test.net.message.proto.Test1Message.Test1Bean.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(testBean_);
                testBean_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Down_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Down_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elex.im.test.net.message.proto.Test1Message.Test1Down.class, com.elex.im.test.net.message.proto.Test1Message.Test1Down.Builder.class);
    }

    /**
     * Protobuf enum {@code Test1Down.MessageEnum}
     */
    public enum MessageEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *第一个值必须是0
       * </pre>
       *
       * <code>First = 0;</code>
       */
      First(0),
      /**
       * <pre>
       *指令
       * </pre>
       *
       * <code>CommondId = 1100101;</code>
       */
      CommondId(1100101),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *第一个值必须是0
       * </pre>
       *
       * <code>First = 0;</code>
       */
      public static final int First_VALUE = 0;
      /**
       * <pre>
       *指令
       * </pre>
       *
       * <code>CommondId = 1100101;</code>
       */
      public static final int CommondId_VALUE = 1100101;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageEnum valueOf(int value) {
        return forNumber(value);
      }

      public static MessageEnum forNumber(int value) {
        switch (value) {
          case 0: return First;
          case 1100101: return CommondId;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageEnum>() {
              public MessageEnum findValueByNumber(int number) {
                return MessageEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.elex.im.test.net.message.proto.Test1Message.Test1Down.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageEnum[] VALUES = values();

      public static MessageEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Test1Down.MessageEnum)
    }

    public static final int TESTBEAN_FIELD_NUMBER = 1;
    private com.elex.im.test.net.message.proto.Test1Message.Test1Bean testBean_;
    /**
     * <pre>
     *测试bean
     * </pre>
     *
     * <code>.Test1Bean testBean = 1;</code>
     */
    public boolean hasTestBean() {
      return testBean_ != null;
    }
    /**
     * <pre>
     *测试bean
     * </pre>
     *
     * <code>.Test1Bean testBean = 1;</code>
     */
    public com.elex.im.test.net.message.proto.Test1Message.Test1Bean getTestBean() {
      return testBean_ == null ? com.elex.im.test.net.message.proto.Test1Message.Test1Bean.getDefaultInstance() : testBean_;
    }
    /**
     * <pre>
     *测试bean
     * </pre>
     *
     * <code>.Test1Bean testBean = 1;</code>
     */
    public com.elex.im.test.net.message.proto.Test1Message.Test1BeanOrBuilder getTestBeanOrBuilder() {
      return getTestBean();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (testBean_ != null) {
        output.writeMessage(1, getTestBean());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (testBean_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTestBean());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elex.im.test.net.message.proto.Test1Message.Test1Down)) {
        return super.equals(obj);
      }
      com.elex.im.test.net.message.proto.Test1Message.Test1Down other = (com.elex.im.test.net.message.proto.Test1Message.Test1Down) obj;

      boolean result = true;
      result = result && (hasTestBean() == other.hasTestBean());
      if (hasTestBean()) {
        result = result && getTestBean()
            .equals(other.getTestBean());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTestBean()) {
        hash = (37 * hash) + TESTBEAN_FIELD_NUMBER;
        hash = (53 * hash) + getTestBean().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elex.im.test.net.message.proto.Test1Message.Test1Down parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Down parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Down parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Down parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Down parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Down parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Down parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Down parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Down parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elex.im.test.net.message.proto.Test1Message.Test1Down parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elex.im.test.net.message.proto.Test1Message.Test1Down prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Test1Down}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Test1Down)
        com.elex.im.test.net.message.proto.Test1Message.Test1DownOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Down_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Down_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elex.im.test.net.message.proto.Test1Message.Test1Down.class, com.elex.im.test.net.message.proto.Test1Message.Test1Down.Builder.class);
      }

      // Construct using com.elex.im.test.net.message.proto.Test1Message.Test1Down.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (testBeanBuilder_ == null) {
          testBean_ = null;
        } else {
          testBean_ = null;
          testBeanBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elex.im.test.net.message.proto.Test1Message.internal_static_Test1Down_descriptor;
      }

      public com.elex.im.test.net.message.proto.Test1Message.Test1Down getDefaultInstanceForType() {
        return com.elex.im.test.net.message.proto.Test1Message.Test1Down.getDefaultInstance();
      }

      public com.elex.im.test.net.message.proto.Test1Message.Test1Down build() {
        com.elex.im.test.net.message.proto.Test1Message.Test1Down result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elex.im.test.net.message.proto.Test1Message.Test1Down buildPartial() {
        com.elex.im.test.net.message.proto.Test1Message.Test1Down result = new com.elex.im.test.net.message.proto.Test1Message.Test1Down(this);
        if (testBeanBuilder_ == null) {
          result.testBean_ = testBean_;
        } else {
          result.testBean_ = testBeanBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elex.im.test.net.message.proto.Test1Message.Test1Down) {
          return mergeFrom((com.elex.im.test.net.message.proto.Test1Message.Test1Down)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elex.im.test.net.message.proto.Test1Message.Test1Down other) {
        if (other == com.elex.im.test.net.message.proto.Test1Message.Test1Down.getDefaultInstance()) return this;
        if (other.hasTestBean()) {
          mergeTestBean(other.getTestBean());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elex.im.test.net.message.proto.Test1Message.Test1Down parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elex.im.test.net.message.proto.Test1Message.Test1Down) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.elex.im.test.net.message.proto.Test1Message.Test1Bean testBean_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.elex.im.test.net.message.proto.Test1Message.Test1Bean, com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder, com.elex.im.test.net.message.proto.Test1Message.Test1BeanOrBuilder> testBeanBuilder_;
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public boolean hasTestBean() {
        return testBeanBuilder_ != null || testBean_ != null;
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public com.elex.im.test.net.message.proto.Test1Message.Test1Bean getTestBean() {
        if (testBeanBuilder_ == null) {
          return testBean_ == null ? com.elex.im.test.net.message.proto.Test1Message.Test1Bean.getDefaultInstance() : testBean_;
        } else {
          return testBeanBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public Builder setTestBean(com.elex.im.test.net.message.proto.Test1Message.Test1Bean value) {
        if (testBeanBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          testBean_ = value;
          onChanged();
        } else {
          testBeanBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public Builder setTestBean(
          com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder builderForValue) {
        if (testBeanBuilder_ == null) {
          testBean_ = builderForValue.build();
          onChanged();
        } else {
          testBeanBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public Builder mergeTestBean(com.elex.im.test.net.message.proto.Test1Message.Test1Bean value) {
        if (testBeanBuilder_ == null) {
          if (testBean_ != null) {
            testBean_ =
              com.elex.im.test.net.message.proto.Test1Message.Test1Bean.newBuilder(testBean_).mergeFrom(value).buildPartial();
          } else {
            testBean_ = value;
          }
          onChanged();
        } else {
          testBeanBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public Builder clearTestBean() {
        if (testBeanBuilder_ == null) {
          testBean_ = null;
          onChanged();
        } else {
          testBean_ = null;
          testBeanBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder getTestBeanBuilder() {
        
        onChanged();
        return getTestBeanFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      public com.elex.im.test.net.message.proto.Test1Message.Test1BeanOrBuilder getTestBeanOrBuilder() {
        if (testBeanBuilder_ != null) {
          return testBeanBuilder_.getMessageOrBuilder();
        } else {
          return testBean_ == null ?
              com.elex.im.test.net.message.proto.Test1Message.Test1Bean.getDefaultInstance() : testBean_;
        }
      }
      /**
       * <pre>
       *测试bean
       * </pre>
       *
       * <code>.Test1Bean testBean = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.elex.im.test.net.message.proto.Test1Message.Test1Bean, com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder, com.elex.im.test.net.message.proto.Test1Message.Test1BeanOrBuilder> 
          getTestBeanFieldBuilder() {
        if (testBeanBuilder_ == null) {
          testBeanBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.elex.im.test.net.message.proto.Test1Message.Test1Bean, com.elex.im.test.net.message.proto.Test1Message.Test1Bean.Builder, com.elex.im.test.net.message.proto.Test1Message.Test1BeanOrBuilder>(
                  getTestBean(),
                  getParentForChildren(),
                  isClean());
          testBean_ = null;
        }
        return testBeanBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Test1Down)
    }

    // @@protoc_insertion_point(class_scope:Test1Down)
    private static final com.elex.im.test.net.message.proto.Test1Message.Test1Down DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elex.im.test.net.message.proto.Test1Message.Test1Down();
    }

    public static com.elex.im.test.net.message.proto.Test1Message.Test1Down getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Test1Down>
        PARSER = new com.google.protobuf.AbstractParser<Test1Down>() {
      public Test1Down parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Test1Down(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Test1Down> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Test1Down> getParserForType() {
      return PARSER;
    }

    public com.elex.im.test.net.message.proto.Test1Message.Test1Down getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Test1Bean_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Test1Bean_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Test1Up_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Test1Up_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Test1Down_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Test1Down_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037test/1100100_Test1Message.proto\"H\n\tTes" +
      "t1Bean\022\r\n\005token\030\001 \001(\t\022\013\n\003rid\030\002 \001(\r\022\021\n\tus" +
      "erIdStr\030\003 \001(\t\022\014\n\004asid\030\004 \001(\r\"R\n\007Test1Up\022\034" +
      "\n\010testBean\030\001 \001(\0132\n.Test1Bean\")\n\013MessageE" +
      "num\022\t\n\005First\020\000\022\017\n\tCommondId\020\304\222C\"T\n\tTest1" +
      "Down\022\034\n\010testBean\030\001 \001(\0132\n.Test1Bean\")\n\013Me" +
      "ssageEnum\022\t\n\005First\020\000\022\017\n\tCommondId\020\305\222CB2\n" +
      "\"com.elex.im.test.net.message.protoB\014Tes" +
      "t1Messageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Test1Bean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Test1Bean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Test1Bean_descriptor,
        new java.lang.String[] { "Token", "Rid", "UserIdStr", "Asid", });
    internal_static_Test1Up_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Test1Up_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Test1Up_descriptor,
        new java.lang.String[] { "TestBean", });
    internal_static_Test1Down_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Test1Down_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Test1Down_descriptor,
        new java.lang.String[] { "TestBean", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
